// frontend/src/app/profile/page.tsx
"use client"

import { ContactMethodsForm } from "@/components/contact-methods-form"
import { useToast } from "@/hooks/use-toast"
import {
  useContactMethods,
  type ContactMethods,
  type ContactMethodsDbInput,
} from "@/hooks/useContactMethods"

export default function ProfilePage() {
  const { loading, contactMethods, saveContactMethods } = useContactMethods()
  const { toast } = useToast()

  const handleSave = async (methods: ContactMethods) => {
    try {
      // Extract only the fields that exist in the database
      const dbMethods: ContactMethodsDbInput = {
        email: methods.email,
        phone: methods.phone,
        preferredMethod: methods.preferred_method,
      }
      await saveContactMethods(dbMethods)
      toast({
        title: "Success",
        description: "Contact methods updated successfully",
      })
    } catch (error) {
      toast({
        title: "Error",
        description:
          error instanceof Error
            ? error.message
            : "Failed to update contact methods",
        variant: "destructive",
      })
    }
  }

  if (loading) {
    return <div>Loading...</div>
  }

  // Convert database contact methods to form interface
  const firstContactMethod = contactMethods[0]
  const formInitialValues: ContactMethods | null = firstContactMethod
    ? {
        email: firstContactMethod.email || "",
        phone: firstContactMethod.phone || "",
        telegram_username: "", // Not in database
        whatsapp: "", // Not in database
        signal: "", // Not in database
        preferred_method:
          ((firstContactMethod as { preferredMethod?: string })
            .preferredMethod as "email" | "phone" | "both" | undefined) ||
          "email",
        check_in_days: 90, // Default value
      }
    : null

  return (
    <div className="container mx-auto max-w-2xl py-8">
      <h1 className="mb-8 text-3xl font-bold">Profile Settings</h1>

      <div className="space-y-8">
        <div>
          <h2 className="mb-4 text-xl font-semibold">Contact Methods</h2>
          <p className="text-muted-foreground mb-6">
            Configure how we can reach you for notifications and alerts.
          </p>
          <ContactMethodsForm
            onSubmit={handleSave}
            initialValues={formInitialValues}
          />
        </div>
      </div>
    </div>
  )
}

// frontend-svelte/src/routes/profile/+page.svelte
<script lang="ts">
	import ContactMethodsForm from '$lib/components/ContactMethodsForm.svelte';
	import type { ContactMethodsFormData } from '$lib/components/ContactMethodsForm.svelte';
	import { toast } from 'svelte-sonner';

	let { data } = $props();

	let initialValues = $derived.by<ContactMethodsFormData | null>(() => {
		const cm = data.contactMethod;
		if (!cm) return null;
		return {
			email: cm.email,
			phone: cm.phone,
			telegram_username: '',
			whatsapp: '',
			signal: '',
			preferred_method: cm.preferredMethod ?? 'email',
			check_in_days: 90
		};
	});

	async function handleSave(methods: ContactMethodsFormData) {
		const response = await fetch('/api/user/contact-methods', {
			method: 'POST',
			headers: { 'Content-Type': 'application/json' },
			body: JSON.stringify({
				email: methods.email || undefined,
				phone: methods.phone || undefined,
				preferredMethod: methods.preferred_method
			})
		});

		if (!response.ok) {
			const body = await response.json().catch(() => null);
			throw new Error(body?.error ?? 'Failed to update contact methods');
		}

		toast.success('Contact methods updated successfully');
	}
</script>

<svelte:head>
	<title>Profile Settings - KeyFate</title>
</svelte:head>

<div class="container mx-auto max-w-2xl py-8">
	<h1 class="mb-8 text-3xl font-bold">Profile Settings</h1>

	<div class="space-y-8">
		<div>
			<h2 class="mb-4 text-xl font-semibold">Contact Methods</h2>
			<p class="text-muted-foreground mb-6">
				Configure how we can reach you for notifications and alerts.
			</p>
			<ContactMethodsForm onSubmit={handleSave} {initialValues} />
		</div>
	</div>
</div>
