// frontend/src/lib/components/Confetti.svelte
<script lang="ts">
	import confetti from 'canvas-confetti';

	let { trigger = false }: { trigger?: boolean } = $props();

	$effect(() => {
		if (trigger) {
			const duration = 3 * 1000;
			const animationEnd = Date.now() + duration;
			const defaults = {
				startVelocity: 30,
				spread: 360,
				ticks: 60,
				zIndex: 9999
			};

			const randomInRange = (min: number, max: number) => Math.random() * (max - min) + min;

			const interval = setInterval(() => {
				const timeLeft = animationEnd - Date.now();

				if (timeLeft <= 0) {
					return clearInterval(interval);
				}

				const particleCount = 50 * (timeLeft / duration);

				// Center burst
				confetti({
					...defaults,
					particleCount,
					origin: { x: randomInRange(0.1, 0.9), y: Math.random() - 0.2 }
				});

				// Left burst
				confetti({
					...defaults,
					particleCount,
					origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 }
				});

				// Right burst
				confetti({
					...defaults,
					particleCount,
					origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 }
				});
			}, 250);

			return () => clearInterval(interval);
		}
	});
</script>

// frontend/src/components/confetti.tsx
"use client"

import confetti from "canvas-confetti"
import { useEffect } from "react"

export function Confetti({ trigger = false }: { trigger?: boolean }) {
  useEffect(() => {
    if (trigger) {
      const duration = 3 * 1000
      const animationEnd = Date.now() + duration
      const defaults = {
        startVelocity: 30,
        spread: 360,
        ticks: 60,
        zIndex: 9999,
      }

      const randomInRange = (min: number, max: number) => {
        return Math.random() * (max - min) + min
      }

      const interval: any = setInterval(function () {
        const timeLeft = animationEnd - Date.now()

        if (timeLeft <= 0) {
          return clearInterval(interval)
        }

        const particleCount = 50 * (timeLeft / duration)

        // Center burst
        confetti(
          Object.assign({}, defaults, {
            particleCount,
            origin: { x: randomInRange(0.1, 0.9), y: Math.random() - 0.2 },
          }),
        )

        // Left burst
        confetti(
          Object.assign({}, defaults, {
            particleCount,
            origin: { x: randomInRange(0.1, 0.3), y: Math.random() - 0.2 },
          }),
        )

        // Right burst
        confetti(
          Object.assign({}, defaults, {
            particleCount,
            origin: { x: randomInRange(0.7, 0.9), y: Math.random() - 0.2 },
          }),
        )
      }, 250)

      return () => clearInterval(interval)
    }
  }, [trigger])

  return null
}
