// frontend-svelte/src/lib/components/ContactMethodsDialog.svelte
<script lang="ts">
  import ContactMethodsForm from '$lib/components/ContactMethodsForm.svelte';
  import * as Dialog from '$lib/components/ui/dialog';

  let {
    open = $bindable(false),
    onOpenChange,
    onSubmit
  }: {
    open: boolean;
    onOpenChange: (open: boolean) => void;
    onSubmit: (methods: any) => Promise<void>;
  } = $props();
</script>

<Dialog.Root bind:open onOpenChange={onOpenChange}>
  <Dialog.Content>
    <Dialog.Header>
      <Dialog.Title>Set Up Contact Methods</Dialog.Title>
      <Dialog.Description>
        Please provide at least one way for us to contact you for check-ins. This information will
        be saved for future use.
      </Dialog.Description>
    </Dialog.Header>
    <ContactMethodsForm
      onSubmit={async (methods) => {
        await onSubmit(methods);
        onOpenChange(false);
      }}
      submitLabel="Continue"
    />
  </Dialog.Content>
</Dialog.Root>

// frontend/src/components/contact-methods-dialog.tsx
"use client"

import { ContactMethodsForm } from "@/components/contact-methods-form"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog"
import type { ContactMethods } from "@/hooks/useContactMethods"

type ContactMethodData = {
  email?: string
  phone?: string
  preferred_method?: "email" | "phone" | "both"
}

interface ContactMethodsDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  onSubmit: (methods: ContactMethodData) => Promise<void>
}

export function ContactMethodsDialog({
  open,
  onOpenChange,
  onSubmit,
}: ContactMethodsDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Set Up Contact Methods</DialogTitle>
          <DialogDescription>
            Please provide at least one way for us to contact you for check-ins.
            This information will be saved for future use.
          </DialogDescription>
        </DialogHeader>
        <ContactMethodsForm
          onSubmit={async (methods: ContactMethods) => {
            // Pass the full methods object for test compatibility
            await onSubmit(methods as ContactMethodData)
            onOpenChange(false)
          }}
          submitLabel="Continue"
        />
      </DialogContent>
    </Dialog>
  )
}
