// frontend-svelte/src/lib/components/NavBar.svelte
<script lang="ts">
  import { page } from '$app/stores';
  import { signOut } from '@auth/sveltekit/client';
  import { Button } from '$lib/components/ui/button';
  import ThemeToggle from '$lib/components/ThemeToggle.svelte';
  import { Crown, LogOut, Menu, Settings, X } from 'lucide-svelte';

  let { session = null }: { session?: any } = $props();

  let pathname = $derived($page.url.pathname);
  let user = $derived(session?.user);

  let userTier = $state<'free' | 'pro'>('free');
  let mobileMenuOpen = $state(false);

  $effect(() => {
    if (!user?.id) return;
    fetch('/api/user/subscription')
      .then((r) => (r.ok ? r.json() : null))
      .then((data) => {
        if (data) userTier = data.tier?.name === 'pro' ? 'pro' : 'free';
      })
      .catch(() => {});
  });

  let isProUser = $derived(userTier === 'pro');

  function handleSignOut() {
    signOut({ callbackUrl: '/auth/signin' });
  }

  const menuItemClass =
    'flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground';

  function isActive(path: string, exact = true) {
    return exact ? pathname === path : pathname.startsWith(path);
  }
</script>

<nav
  class="bg-background/95 supports-[backdrop-filter]:bg-background/60 border-b backdrop-blur"
>
  <div class="container mx-auto px-4">
    <div class="flex h-16 items-center justify-between">
      <div class="flex items-center space-x-4">
        <a href={user ? '/dashboard' : '/'} class="flex items-center">
          <!-- Mobile icons -->
          <img
            src="/img/icon-light.png"
            alt="KeyFate"
            width="40"
            height="40"
            class="block h-10 w-10 sm:hidden dark:hidden"
          />
          <img
            src="/img/icon-dark.png"
            alt="KeyFate"
            width="40"
            height="40"
            class="hidden h-10 w-10 dark:block dark:sm:hidden"
          />
          <!-- Desktop logos -->
          <img
            src="/img/logo-light.png"
            alt="KeyFate"
            width="200"
            height="40"
            class="hidden h-10 w-auto sm:block dark:sm:hidden"
          />
          <img
            src="/img/logo-dark.png"
            alt="KeyFate"
            width="200"
            height="40"
            class="hidden h-10 w-auto dark:sm:block"
          />
        </a>

        <div class="hidden items-center space-x-1 md:flex">
          {#if user}
            <a
              href="/dashboard"
              class="rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground {isActive(
                '/dashboard'
              )
                ? 'bg-accent text-accent-foreground'
                : ''}"
            >
              Dashboard
            </a>
          {/if}

          {#if !user}
            <a
              href="/pricing"
              class="rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground {isActive(
                '/pricing'
              )
                ? 'bg-accent text-accent-foreground'
                : ''}"
            >
              Pricing
            </a>
          {/if}

          <a
            href="/blog"
            class="rounded-md px-3 py-2 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground {isActive(
              '/blog',
              false
            )
              ? 'bg-accent text-accent-foreground'
              : ''}"
          >
            Blog
          </a>
        </div>
      </div>

      <div class="flex items-center space-x-2">
        <Button
          variant="ghost"
          size="sm"
          href="/decrypt"
          class="hidden md:flex {isActive('/decrypt')
            ? 'bg-accent text-accent-foreground'
            : ''}"
        >
          Recover Secret
        </Button>

        <ThemeToggle />

        {#if isProUser}
          <Button
            variant="outline"
            size="sm"
            class="border-primary text-primary hover:bg-primary hover:text-primary-foreground hidden md:flex"
          >
            <Crown class="h-4 w-4" />
            Pro
          </Button>
        {/if}

        {#if !user}
          <Button variant="ghost" size="sm" href="/auth/signin" class="hidden md:flex">
            Sign In
          </Button>
          <Button variant="default" size="sm" href="/auth/signin">Sign Up</Button>
        {/if}

        {#if user}
          <!-- Desktop account dropdown -->
          <div class="relative hidden md:block">
            <Button
              variant="ghost"
              size="sm"
              onclick={() => (mobileMenuOpen = !mobileMenuOpen)}
            >
              Account
            </Button>
            {#if mobileMenuOpen}
              <!-- svelte-ignore a11y_no_static_element_interactions -->
              <!-- svelte-ignore a11y_click_events_have_key_events -->
              <div
                class="fixed inset-0 z-40"
                onclick={() => (mobileMenuOpen = false)}
              ></div>
              <div
                class="absolute right-0 z-50 mt-2 w-[200px] rounded-md border bg-popover p-2 shadow-md"
              >
                <a
                  href="/settings"
                  class="{menuItemClass} {isActive('/settings')
                    ? 'bg-accent text-accent-foreground'
                    : ''}"
                  onclick={() => (mobileMenuOpen = false)}
                >
                  <Settings class="h-4 w-4" />
                  <span>Settings</span>
                </a>
                {#if !isProUser}
                  <a
                    href="/pricing"
                    class="{menuItemClass} {isActive('/pricing')
                      ? 'bg-accent text-accent-foreground'
                      : ''}"
                    onclick={() => (mobileMenuOpen = false)}
                  >
                    <Crown class="h-4 w-4" />
                    <span>Upgrade to Pro</span>
                  </a>
                {/if}
                <button class="{menuItemClass} w-full text-left" onclick={handleSignOut}>
                  <LogOut class="h-4 w-4" />
                  <span>Sign Out</span>
                </button>
              </div>
            {/if}
          </div>
        {/if}

        <!-- Mobile menu button -->
        <Button
          variant="ghost"
          size="icon"
          class="md:hidden"
          onclick={() => (mobileMenuOpen = !mobileMenuOpen)}
          data-testid="mobile-menu-trigger"
        >
          {#if mobileMenuOpen}
            <X class="h-5 w-5" />
          {:else}
            <Menu class="h-5 w-5" />
          {/if}
          <span class="sr-only">Open menu</span>
        </Button>
      </div>
    </div>

    <!-- Mobile menu -->
    {#if mobileMenuOpen}
      <div class="border-t pb-4 md:hidden" data-testid="dropdown-content">
        <div class="space-y-1 pt-2">
          {#if !user}
            <a
              href="/pricing"
              class="{menuItemClass} {isActive('/pricing')
                ? 'bg-accent text-accent-foreground'
                : ''}"
              onclick={() => (mobileMenuOpen = false)}
            >
              Pricing
            </a>
          {/if}

          {#if user}
            <a
              href="/dashboard"
              class="{menuItemClass} {isActive('/dashboard')
                ? 'bg-accent text-accent-foreground'
                : ''}"
              onclick={() => (mobileMenuOpen = false)}
            >
              Dashboard
            </a>
            <a
              href="/settings"
              class="{menuItemClass} {isActive('/settings')
                ? 'bg-accent text-accent-foreground'
                : ''}"
              onclick={() => (mobileMenuOpen = false)}
            >
              <Settings class="h-4 w-4" />
              Settings
            </a>
          {/if}

          <a
            href="/decrypt"
            class="{menuItemClass} {isActive('/decrypt')
              ? 'bg-accent text-accent-foreground'
              : ''}"
            data-testid="mobile-recover-secret"
            onclick={() => (mobileMenuOpen = false)}
          >
            Recover Secret
          </a>

          {#if user}
            {#if !isProUser}
              <a
                href="/pricing"
                class="{menuItemClass} {isActive('/pricing')
                  ? 'bg-accent text-accent-foreground'
                  : ''}"
                onclick={() => (mobileMenuOpen = false)}
              >
                <Crown class="h-4 w-4" />
                Upgrade to Pro
              </a>
            {/if}
            <button class="{menuItemClass} w-full text-left" onclick={handleSignOut}>
              <LogOut class="h-4 w-4" />
              Sign Out
            </button>
          {/if}

          {#if !user}
            <a
              href="/auth/signin"
              class={menuItemClass}
              onclick={() => (mobileMenuOpen = false)}
            >
              Sign In
            </a>
          {/if}
        </div>
      </div>
    {/if}
  </div>
</nav>

// frontend/src/components/nav-bar.tsx
"use client"

import { WelcomeToProModal } from "@/components/subscription/WelcomeToProModal"
import { ThemeToggle } from "@/components/theme-toggle"
import { Button } from "@/components/ui/button"
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu"
import { useConfig } from "@/contexts/ConfigContext"
import { cn } from "@/lib/utils"
import { Crown, LogOut, Menu, Settings } from "lucide-react"
import { signOut, useSession } from "next-auth/react"

import Image from "next/image"
import Link from "next/link"
import { usePathname } from "next/navigation"
import { useEffect, useState } from "react"

export function NavBar() {
  const pathname = usePathname()
  const { data: session, status } = useSession()
  const { config } = useConfig()

  const [userTier, setUserTier] = useState<"free" | "pro">("free")
  const [checkingSubscription, setCheckingSubscription] = useState(false)
  const [proModalOpen, setProModalOpen] = useState(false)
  const user = session?.user as
    | { id?: string; name?: string; email?: string; image?: string }
    | undefined
  const loading = status === "loading"

  useEffect(() => {
    async function fetchUserTier() {
      if (!user?.id) return

      setCheckingSubscription(true)
      try {
        const response = await fetch("/api/user/subscription")
        if (response.ok) {
          const data = await response.json()
          setUserTier(data.tier?.name === "pro" ? "pro" : "free")
        }
      } catch (error) {
        console.error("Failed to fetch user tier:", error)
      } finally {
        setCheckingSubscription(false)
      }
    }

    fetchUserTier()
  }, [user?.id])

  const isProUser = userTier === "pro"

  const handleSignOut = async () => {
    await signOut({ callbackUrl: "/auth/signin" })
  }

  return (
    <nav className="bg-background/95 supports-[backdrop-filter]:bg-background/60 border-b backdrop-blur">
      <div className="container mx-auto px-4">
        <div className="flex h-16 items-center justify-between">
          <div className="flex items-center space-x-4">
            <Link
              href={user ? "/dashboard" : "/"}
              className="flex items-center"
            >
              {/* Mobile icons */}
              <Image
                src="/img/icon-light.png"
                alt={config?.company || "KeyFate"}
                width={40}
                height={40}
                className="block h-10 w-10 sm:hidden dark:hidden"
                priority
              />
              <Image
                src="/img/icon-dark.png"
                alt={config?.company || "KeyFate"}
                width={40}
                height={40}
                className="hidden h-10 w-10 dark:block dark:sm:hidden"
                priority
              />
              {/* Desktop logos */}
              <Image
                src="/img/logo-light.png"
                alt={config?.company || "KeyFate"}
                width={200}
                height={40}
                className="hidden h-10 w-auto sm:block dark:sm:hidden"
                priority
              />
              <Image
                src="/img/logo-dark.png"
                alt={config?.company || "KeyFate"}
                width={200}
                height={40}
                className="hidden h-10 w-auto dark:sm:block"
                priority
              />
            </Link>

            <NavigationMenu className="hidden md:flex">
              <NavigationMenuList>
                {user && (
                  <NavigationMenuItem>
                    <NavigationMenuLink asChild>
                      <Link
                        href="/dashboard"
                        className={cn(
                          navigationMenuTriggerStyle(),
                          pathname === "/dashboard" &&
                            "bg-accent text-accent-foreground",
                        )}
                      >
                        Dashboard
                      </Link>
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                )}

                {!loading && !user && (
                  <NavigationMenuItem>
                    <NavigationMenuLink asChild>
                      <Link
                        href="/pricing"
                        className={cn(
                          navigationMenuTriggerStyle(),
                          pathname === "/pricing" &&
                            "bg-accent text-accent-foreground",
                        )}
                      >
                        Pricing
                      </Link>
                    </NavigationMenuLink>
                  </NavigationMenuItem>
                )}

                <NavigationMenuItem>
                  <NavigationMenuLink asChild>
                    <Link
                      href="/blog"
                      className={cn(
                        navigationMenuTriggerStyle(),
                        pathname?.startsWith("/blog") &&
                          "bg-accent text-accent-foreground",
                      )}
                    >
                      Blog
                    </Link>
                  </NavigationMenuLink>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </div>

          <div className="flex items-center space-x-2">
            <Button
              variant="ghost"
              size="sm"
              asChild
              className={cn(
                "hidden md:flex",
                pathname === "/decrypt" && "bg-accent text-accent-foreground",
              )}
            >
              <Link href="/decrypt">Recover Secret</Link>
            </Button>

            <ThemeToggle />

            {!checkingSubscription && isProUser && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setProModalOpen(true)}
                className="border-primary text-primary hover:bg-primary hover:text-primary-foreground hidden md:flex"
              >
                <Crown className="h-4 w-4" />
                Pro
              </Button>
            )}

            {!loading && !user && (
              <>
                <Button
                  variant="ghost"
                  size="sm"
                  asChild
                  className="hidden md:flex"
                >
                  <Link href="/auth/signin">Sign In</Link>
                </Button>
                <Button variant="default" size="sm" asChild>
                  <Link href="/auth/signin">Sign Up</Link>
                </Button>
              </>
            )}

            {user && (
              <NavigationMenu className="hidden justify-end md:flex">
                <NavigationMenuList>
                  <NavigationMenuItem>
                    <NavigationMenuTrigger>Account</NavigationMenuTrigger>
                    <NavigationMenuContent className="!left-auto !right-0">
                      <ul className="grid w-[200px] gap-1 p-2">
                        <li>
                          <NavigationMenuLink asChild>
                            <Link
                              href="/settings"
                              className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/settings" ? "bg-accent text-accent-foreground" : ""}`}
                            >
                              <Settings className="h-4 w-4" />
                              <span>Settings</span>
                            </Link>
                          </NavigationMenuLink>
                        </li>
                        {!checkingSubscription && !isProUser && (
                          <li>
                            <NavigationMenuLink asChild>
                              <Link
                                href="/pricing"
                                className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/pricing" ? "bg-accent text-accent-foreground" : ""}`}
                              >
                                <Crown className="h-4 w-4" />
                                <span>Upgrade to Pro</span>
                              </Link>
                            </NavigationMenuLink>
                          </li>
                        )}
                        <li>
                          <button
                            onClick={handleSignOut}
                            className="hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex w-full select-none items-center gap-2 rounded-md px-3 py-2 text-left leading-none outline-none transition-colors"
                          >
                            <LogOut className="h-4 w-4" />
                            <span>Sign Out</span>
                          </button>
                        </li>
                      </ul>
                    </NavigationMenuContent>
                  </NavigationMenuItem>
                </NavigationMenuList>
              </NavigationMenu>
            )}

            <NavigationMenu className="md:hidden">
              <NavigationMenuList>
                <NavigationMenuItem>
                  <NavigationMenuTrigger
                    className="h-9 px-3"
                    data-testid="mobile-menu-trigger"
                  >
                    <Menu className="h-5 w-5" />
                    <span className="sr-only">Open menu</span>
                  </NavigationMenuTrigger>
                  <NavigationMenuContent data-testid="dropdown-content">
                    <ul className="grid w-[280px] gap-1 p-2">
                      {!user && (
                        <li>
                          <NavigationMenuLink asChild>
                            <Link
                              href="/pricing"
                              className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground block select-none rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/pricing" ? "bg-accent text-accent-foreground" : ""}`}
                            >
                              Pricing
                            </Link>
                          </NavigationMenuLink>
                        </li>
                      )}

                      {user && (
                        <>
                          <li>
                            <NavigationMenuLink asChild>
                              <Link
                                href="/dashboard"
                                className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/dashboard" ? "bg-accent text-accent-foreground" : ""}`}
                              >
                                Dashboard
                              </Link>
                            </NavigationMenuLink>
                          </li>
                          <li>
                            <NavigationMenuLink asChild>
                              <Link
                                href="/settings"
                                className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/settings" ? "bg-accent text-accent-foreground" : ""}`}
                              >
                                <Settings className="h-4 w-4" />
                                Settings
                              </Link>
                            </NavigationMenuLink>
                          </li>
                        </>
                      )}

                      <li>
                        <NavigationMenuLink asChild>
                          <Link
                            href="/decrypt"
                            className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/decrypt" ? "bg-accent text-accent-foreground" : ""}`}
                            data-testid="mobile-recover-secret"
                          >
                            Recover Secret
                          </Link>
                        </NavigationMenuLink>
                      </li>

                      {!loading && user && (
                        <>
                          {!checkingSubscription && !isProUser && (
                            <li>
                              <NavigationMenuLink asChild>
                                <Link
                                  href="/pricing"
                                  className={`hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex select-none items-center gap-2 rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors ${pathname === "/pricing" ? "bg-accent text-accent-foreground" : ""}`}
                                >
                                  <Crown className="h-4 w-4" />
                                  Upgrade to Pro
                                </Link>
                              </NavigationMenuLink>
                            </li>
                          )}
                          <li>
                            <button
                              onClick={handleSignOut}
                              className="hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground flex w-full select-none items-center gap-2 rounded-md px-3 py-2 text-left leading-none outline-none transition-colors"
                            >
                              <LogOut className="h-4 w-4" />
                              Sign Out
                            </button>
                          </li>
                        </>
                      )}

                      {!loading && !user && (
                        <li>
                          <NavigationMenuLink asChild>
                            <Link
                              href="/auth/signin"
                              className="hover:bg-accent hover:text-accent-foreground focus:bg-accent focus:text-accent-foreground block select-none rounded-md px-3 py-2 leading-none no-underline outline-none transition-colors"
                            >
                              Sign In
                            </Link>
                          </NavigationMenuLink>
                        </li>
                      )}
                    </ul>
                  </NavigationMenuContent>
                </NavigationMenuItem>
              </NavigationMenuList>
            </NavigationMenu>
          </div>
        </div>
      </div>
      <WelcomeToProModal open={proModalOpen} onOpenChange={setProModalOpen} />
    </nav>
  )
}
