// frontend/src/lib/components/SSSDecryptor.svelte
<script lang="ts">
	import { untrack } from 'svelte';
	import * as Alert from '$lib/components/ui/alert';
	import { Button } from '$lib/components/ui/button';
	import { Textarea } from '$lib/components/ui/textarea';
	import { toast } from 'svelte-sonner';
	import { Buffer } from 'buffer';
	import { Check, Copy, Info, PlusCircle, ShieldAlert, ShieldCheck, Trash2 } from '@lucide/svelte';
	import sss from 'shamirs-secret-sharing';

	let {
		initialShares = [],
		companyName = 'KeyFate'
	}: {
		initialShares?: string[];
		companyName?: string;
	} = $props();

	let shares = $state<string[]>(
		untrack(() =>
			initialShares.length === 0
				? ['', '']
				: initialShares.length === 1
					? [initialShares[0], '']
					: [...initialShares]
		)
	);
	let recoveredSecret = $state<string | null>(null);
	let error = $state<string | null>(null);
	let isLoading = $state(false);
	let isCopied = $state(false);

	function handleShareChange(index: number, value: string) {
		shares[index] = value.trim();
		recoveredSecret = null;
		error = null;
	}

	function addShareInput() {
		shares = [...shares, ''];
	}

	function removeShareInput(index: number) {
		if (shares.length <= 2) {
			error = 'You need at least two shares to attempt recovery.';
			return;
		}
		shares = shares.filter((_, i) => i !== index);
	}

	function handleCombineShares() {
		isLoading = true;
		error = null;
		recoveredSecret = null;

		const validShares = shares.filter((s) => s.trim() !== '');
		if (validShares.length < 2) {
			error = 'Please provide at least two shares.';
			isLoading = false;
			return;
		}

		try {
			const shareBuffers = validShares.map((shareHex) => {
				if (!/^[0-9a-fA-F]+$/.test(shareHex)) {
					throw new Error(
						`Invalid share format: "${shareHex.substring(0, 10)}...". Shares should be hexadecimal strings.`
					);
				}
				const sanitizedHex = shareHex.length % 2 !== 0 ? '0' + shareHex : shareHex;
				if (sanitizedHex.length === 0) {
					throw new Error('Empty share provided after sanitization.');
				}
				return Buffer.from(sanitizedHex, 'hex');
			});

			if (shareBuffers.length > 1) {
				const firstLength = shareBuffers[0].length;
				if (!shareBuffers.every((b) => b.length === firstLength)) {
					throw new Error(
						'Shares are not of the same length. Ensure you have copied them correctly.'
					);
				}
			}

			const recovered = sss.combine(shareBuffers);
			recoveredSecret = recovered.toString('utf8');
		} catch (e) {
			console.error('Error combining shares:', e);
			const errorMessage = e instanceof Error ? e.message : 'Invalid shares or threshold not met.';
			error = `Failed to recover secret: ${errorMessage}. Ensure shares are correct, in hexadecimal format, and you have enough of them.`;
		} finally {
			isLoading = false;
		}
	}

	async function handleCopySecret() {
		if (!recoveredSecret) return;

		try {
			await navigator.clipboard.writeText(recoveredSecret);
			isCopied = true;
			toast.success('Secret copied to clipboard successfully.');
			setTimeout(() => {
				isCopied = false;
			}, 2000);
		} catch (err) {
			console.error('Error copying secret:', err);
			toast.error('Failed to copy secret to clipboard.');
		}
	}
</script>

<div class="space-y-6">
	<div class="text-center">
		<h1 class="font-space mb-4 text-3xl font-bold">Secret Recovery</h1>
	</div>

	<div class="space-y-6">
		<div>
			<h2 class="font-space mb-2 text-xl font-semibold">Enter Your Shares</h2>
			<p class="text-muted-foreground text-sm">
				Enter your {companyName} shares below. You need a minimum number of correct shares (as per the
				threshold set during creation) to recover the original secret (shares are typically hexadecimal
				strings).
			</p>
		</div>

		<div class="space-y-4">
			{#each shares as share, index}
				<div class="flex items-center space-x-2">
					<Textarea
						placeholder={`Share ${index + 1} (from ${companyName} or your trusted contact)`}
						value={share}
						oninput={(e) => handleShareChange(index, (e.target as HTMLTextAreaElement).value)}
						rows={2}
						class="flex-grow font-mono text-sm"
						disabled={isLoading}
					/>
					{#if shares.length > 2}
						<Button
							variant="ghost"
							size="icon"
							onclick={() => removeShareInput(index)}
							disabled={isLoading}
							aria-label="Remove share"
						>
							<Trash2 class="h-4 w-4" />
						</Button>
					{/if}
				</div>
			{/each}
			<Button
				type="button"
				variant="outline"
				onclick={addShareInput}
				disabled={isLoading}
				class="w-full sm:w-auto"
			>
				<PlusCircle class="mr-2 h-4 w-4" /> Add Another Share
			</Button>
		</div>

		<Button
			type="button"
			onclick={handleCombineShares}
			disabled={isLoading || shares.filter((s) => s.trim() !== '').length < 2}
			class="w-full text-lg"
			size="lg"
		>
			{isLoading ? 'Recovering...' : 'Recover Secret'}
		</Button>

		{#if error}
			<Alert.Root variant="destructive">
				<ShieldAlert class="h-4 w-4" />
				<Alert.Title>Recovery Failed</Alert.Title>
				<Alert.Description>{error}</Alert.Description>
			</Alert.Root>
		{/if}

		{#if recoveredSecret}
			<Alert.Root variant="default" class="border-accent bg-accent/50">
				<ShieldCheck class="text-accent-foreground h-4 w-4" />
				<Alert.Title class="text-accent-foreground">Secret Recovered Successfully!</Alert.Title>
				<Alert.Description class="space-y-2">
					<p class="text-accent-foreground/90">Your original secret is:</p>
					<Textarea
						value={recoveredSecret}
						readonly
						rows={4}
						class="bg-muted mt-2 w-full rounded-md border p-3 font-mono text-sm select-all"
					/>
					<Button
						type="button"
						variant={isCopied ? 'default' : 'outline'}
						size="sm"
						class="mt-2 transition-all duration-200"
						onclick={handleCopySecret}
						disabled={isCopied}
					>
						{#if isCopied}
							<Check class="mr-2 h-3 w-3" /> Copied!
						{:else}
							<Copy class="mr-2 h-3 w-3" /> Copy Recovered Secret
						{/if}
					</Button>
				</Alert.Description>
			</Alert.Root>
		{/if}
	</div>

	<div class="bg-muted/30 rounded-lg p-4">
		<div class="flex items-start space-x-3">
			<Info class="text-muted-foreground mt-0.5 h-4 w-4" />
			<div class="space-y-2 text-sm">
				<p class="text-muted-foreground">
					<strong>Educational demonstration:</strong> This tool runs entirely in your browser. Your shares
					are processed locally and never sent to servers. For maximum security with sensitive secrets,
					we recommend running this tool locally on your own device.
				</p>
				<a href="/local-instructions" class="text-muted-foreground h-auto p-0 text-xs underline">
					Get setup instructions for local use &rarr;
				</a>
			</div>
		</div>
	</div>
</div>

// frontend/src/components/sss-decryptor.tsx
"use client"

import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { useConfig } from "@/contexts/ConfigContext"
import { useToast } from "@/hooks/use-toast"
import { Buffer } from "buffer"
import {
  Check,
  Copy,
  Info,
  PlusCircle,
  ShieldAlert,
  ShieldCheck,
  Trash2,
} from "lucide-react"
import Link from "next/link"
import { useEffect, useRef, useState } from "react"
import sss from "shamirs-secret-sharing"

type SssDecryptorProps = {
  initialShares?: string[]
}

export function SssDecryptor({ initialShares = [] }: SssDecryptorProps) {
  const { toast } = useToast()
  const { config } = useConfig()
  const firstTextareaRef = useRef<HTMLTextAreaElement>(null)
  const secondTextareaRef = useRef<HTMLTextAreaElement>(null)

  const [shares, setShares] = useState<string[]>(() => {
    // Initialize with at least two empty strings if no initial shares, or fill with initialShares
    const defaults = ["", ""]
    if (initialShares.length === 0) return defaults
    if (initialShares.length === 1) return [initialShares[0], ""]
    return initialShares
  })
  const [recoveredSecret, setRecoveredSecret] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [isLoading, setIsLoading] = useState(false)
  const [isCopied, setIsCopied] = useState(false)

  // Focus the appropriate textarea when component mounts
  useEffect(() => {
    if (shares[0] && shares[0].trim() !== "" && secondTextareaRef.current) {
      // If first share is filled, focus on second textarea
      secondTextareaRef.current.focus()
    } else if (firstTextareaRef.current) {
      // If first share is empty, focus on first textarea
      firstTextareaRef.current.focus()
    }
  }, [shares])

  const handleShareChange = (index: number, value: string) => {
    const newShares = [...shares]
    newShares[index] = value.trim()
    setShares(newShares)
    setRecoveredSecret(null) // Clear previous result when shares change
    setError(null)
  }

  const addShareInput = () => {
    setShares([...shares, ""])
  }

  const removeShareInput = (index: number) => {
    if (shares.length <= 2) {
      setError("You need at least two shares to attempt recovery.")
      return
    }
    const newShares = shares.filter((_, i) => i !== index)
    setShares(newShares)
  }

  const handleCombineShares = () => {
    setIsLoading(true)
    setError(null)
    setRecoveredSecret(null)

    const validShares = shares.filter((s) => s.trim() !== "")
    if (validShares.length < 2) {
      setError("Please provide at least two shares.")
      setIsLoading(false)
      return
    }

    try {
      const shareBuffers = validShares.map((shareHex) => {
        if (!/^[0-9a-fA-F]+$/.test(shareHex)) {
          throw new Error(
            `Invalid share format: "${shareHex.substring(0, 10)}...". Shares should be hexadecimal strings.`,
          )
        }
        // Ensure hex string has an even length for Buffer.from(..., \'hex\')
        const sanitizedHex =
          shareHex.length % 2 !== 0 ? "0" + shareHex : shareHex
        if (sanitizedHex.length === 0) {
          throw new Error("Empty share provided after sanitization.")
        }
        return Buffer.from(sanitizedHex, "hex")
      })

      // Basic validation: Check if all buffers have the same length (SSS requirement)
      if (shareBuffers.length > 1) {
        const firstLength = shareBuffers[0].length
        if (!shareBuffers.every((b) => b.length === firstLength)) {
          throw new Error(
            "Shares are not of the same length. Ensure you have copied them correctly.",
          )
        }
      }

      const recovered = sss.combine(shareBuffers)
      setRecoveredSecret(recovered.toString("utf8"))
    } catch (e) {
      console.error("Error combining shares:", e)
      const errorMessage =
        e instanceof Error ? e.message : "Invalid shares or threshold not met."
      setError(
        `Failed to recover secret: ${errorMessage}. Ensure shares are correct, in hexadecimal format, and you have enough of them.`,
      )
    } finally {
      setIsLoading(false)
    }
  }

  const handleCopySecret = async () => {
    if (!recoveredSecret) return

    try {
      await navigator.clipboard.writeText(recoveredSecret)
      setIsCopied(true)
      toast({
        title: "Copied!",
        description: "Secret copied to clipboard successfully.",
        duration: 3000,
      })

      // Reset the copied state after 2 seconds
      setTimeout(() => {
        setIsCopied(false)
      }, 2000)
    } catch (error) {
      console.error("Error copying secret:", error)
      toast({
        title: "Copy failed",
        description: "Failed to copy secret to clipboard.",
        variant: "destructive",
        duration: 3000,
      })
    }
  }

  return (
    <div className="space-y-6">
      <div className="text-center">
        <h1 className="mb-4 text-3xl font-bold">Secret Recovery</h1>
      </div>

      <div className="space-y-6 rounded-lg border p-6 shadow-md">
        <div>
          <h2 className="mb-2 text-xl font-semibold">Enter Your Shares</h2>
          <p className="text-muted-foreground text-sm">
            Enter your {config?.company || "KeyFate"} shares below. You need a
            minimum number of correct shares (as per the threshold set during
            creation) to recover the original secret (shares are typically
            hexadecimal strings).
          </p>
        </div>

        <div className="space-y-4">
          {shares.map((share, index) => (
            <div key={index} className="flex items-center space-x-2">
              <Textarea
                ref={
                  index === 0
                    ? firstTextareaRef
                    : index === 1
                      ? secondTextareaRef
                      : undefined
                }
                placeholder={`Share ${index + 1} (from ${config?.company || "KeyFate"} or your trusted contact)`}
                value={share}
                onChange={(e) => handleShareChange(index, e.target.value)}
                rows={2}
                className="flex-grow font-mono text-sm"
                disabled={isLoading}
              />
              {shares.length > 2 && (
                <Button
                  variant="ghost"
                  size="icon"
                  onClick={() => removeShareInput(index)}
                  disabled={isLoading}
                  aria-label="Remove share"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              )}
            </div>
          ))}
          <Button
            type="button"
            variant="outline"
            onClick={addShareInput}
            disabled={isLoading}
            className="w-full sm:w-auto"
          >
            <PlusCircle className="mr-2 h-4 w-4" /> Add Another Share
          </Button>
        </div>

        <Button
          type="button"
          onClick={handleCombineShares}
          disabled={
            isLoading || shares.filter((s) => s.trim() !== "").length < 2
          }
          className="w-full text-lg"
          size="lg"
        >
          {isLoading ? "Recovering..." : "Recover Secret"}
        </Button>

        {error && (
          <Alert variant="destructive">
            <ShieldAlert className="h-4 w-4" />
            <AlertTitle>Recovery Failed</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        {recoveredSecret && (
          <Alert variant="default" className="border-accent bg-accent/50">
            <ShieldCheck className="text-accent-foreground h-4 w-4" />
            <AlertTitle className="text-accent-foreground">
              Secret Recovered Successfully!
            </AlertTitle>
            <AlertDescription className="space-y-2">
              <p className="text-accent-foreground/90">
                Your original secret is:
              </p>
              <Textarea
                value={recoveredSecret}
                readOnly
                rows={4}
                className="bg-muted mt-2 w-full select-all rounded-md border p-3 font-mono text-sm"
              />
              <Button
                type="button"
                variant={isCopied ? "default" : "outline"}
                size="sm"
                className="mt-2 transition-all duration-200"
                onClick={handleCopySecret}
                disabled={isCopied}
              >
                {isCopied ? (
                  <>
                    <Check className="mr-2 h-3 w-3" /> Copied!
                  </>
                ) : (
                  <>
                    <Copy className="mr-2 h-3 w-3" /> Copy Recovered Secret
                  </>
                )}
              </Button>
            </AlertDescription>
          </Alert>
        )}
      </div>

      <div className="border-muted bg-muted/30 rounded-lg border p-4">
        <div className="flex items-start space-x-3">
          <Info className="text-muted-foreground mt-0.5 h-4 w-4" />
          <div className="space-y-2 text-sm">
            <p className="text-muted-foreground">
              <strong>Educational demonstration:</strong> This tool runs
              entirely in your browser. Your shares are processed locally and
              never sent to servers. For maximum security with sensitive
              secrets, we recommend running this tool locally on your own
              device.
            </p>
            <Button
              variant="link"
              size="sm"
              asChild
              className="text-muted-foreground h-auto p-0 text-xs underline"
            >
              <Link href="/local-instructions">
                Get setup instructions for local use →
              </Link>
            </Button>
          </div>
        </div>
      </div>
    </div>
  )
}
