// frontend/src/app/(authenticated)/settings/subscription/page.tsx
import type { Session } from "next-auth"
import { authConfig } from "@/lib/auth-config"
import { getServerSession } from "next-auth/next"
import { redirect } from "next/navigation"
import { getUserTierInfo } from "@/lib/subscription"
import { SubscriptionManagement } from "@/components/settings/SubscriptionManagement"
import { SettingsPageHeader } from "@/components/settings/SettingsPageHeader"

export default async function SubscriptionSettingsPage() {
  const session = (await getServerSession(authConfig)) as Session | null

  if (!session?.user?.id) {
    redirect("/sign-in")
  }

  const userId = session.user.id
  const tierInfo = await getUserTierInfo(userId)

  if (!tierInfo) {
    return <div>Error loading subscription information</div>
  }

  return (
    <div className="space-y-6">
      <SettingsPageHeader
        title="Subscription"
        description="Manage your subscription and billing"
      />

      <SubscriptionManagement tierInfo={tierInfo} />
    </div>
  )
}

// frontend/src/routes/(authenticated)/settings/subscription/+page.svelte
<script lang="ts">
	import SubscriptionManager from '$lib/components/SubscriptionManager.svelte';

	let { data } = $props();
</script>

<svelte:head>
	<title>Subscription - KeyFate</title>
</svelte:head>

<div class="space-y-8">
	<div>
		<h2 class="font-space text-xl font-bold tracking-tight">Subscription</h2>
		<p class="text-muted-foreground mt-1 text-sm">Manage your subscription and billing</p>
	</div>

	{#if data.tierInfo}
		<SubscriptionManager tierInfo={data.tierInfo} />
	{:else}
		<div class="border-destructive/50 rounded-lg border p-4">
			<p class="text-destructive text-sm">Error loading subscription information</p>
		</div>
	{/if}
</div>
