// frontend/src/app/(authenticated)/settings/audit/page.tsx
import { authConfig } from "@/lib/auth-config"
import { AuditLogsPage } from "@/components/audit/AuditLogsPage"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { getUserTierInfo } from "@/lib/subscription"
import type { Session } from "next-auth"
import { getServerSession } from "next-auth/next"
import Link from "next/link"
import { redirect } from "next/navigation"
import { SettingsPageHeader } from "@/components/settings/SettingsPageHeader"

export default async function AuditLogsRoute() {
  const session = (await getServerSession(authConfig)) as Session | null

  if (!session?.user?.id) {
    redirect("/sign-in")
  }

  const tierInfo = await getUserTierInfo(session.user.id)
  const userTier = (tierInfo?.tier?.tiers?.name ?? "free") as "free" | "pro"

  if (userTier !== "pro") {
    return (
      <div className="space-y-6">
        <SettingsPageHeader
          title="Audit Logs"
          description="Comprehensive audit trails are a Pro feature"
        />

        <Card>
          <CardHeader>
            <CardTitle>Audit Logs</CardTitle>
            <CardDescription>
              Comprehensive audit trails are a Pro feature
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <p className="text-muted-foreground">
                Upgrade to Pro to access comprehensive audit logs that track all
                activities in your account, including:
              </p>
              <ul className="text-muted-foreground list-inside list-disc space-y-2">
                <li>Secret creation, editing, and deletion</li>
                <li>Check-in activity</li>
                <li>Recipient management</li>
                <li>Login events</li>
                <li>Subscription changes</li>
                <li>Settings updates</li>
              </ul>
              <div className="flex gap-4 pt-4">
                <Button asChild>
                  <Link href="/pricing">Upgrade to Pro</Link>
                </Button>
                <Button variant="outline" asChild>
                  <Link href="/dashboard">Back to Dashboard</Link>
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <SettingsPageHeader
        title="Audit Logs"
        description="Comprehensive audit trail of all activities in your account"
      />

      <AuditLogsPage />
    </div>
  )
}

// frontend-svelte/src/routes/(authenticated)/settings/audit/+page.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card';
	import AuditLogsPage from '$lib/components/AuditLogsPage.svelte';

	let { data } = $props();
</script>

<svelte:head>
	<title>Audit Logs - KeyFate</title>
</svelte:head>

<div class="space-y-6">
	<div>
		<h2 class="text-2xl font-bold tracking-tight">Audit Logs</h2>
		<p class="text-muted-foreground">
			{data.userTier === 'pro'
				? 'Comprehensive audit trail of all activities in your account'
				: 'Comprehensive audit trails are a Pro feature'}
		</p>
	</div>

	{#if data.userTier !== 'pro'}
		<Card.Root>
			<Card.Header>
				<Card.Title>Audit Logs</Card.Title>
				<Card.Description>Comprehensive audit trails are a Pro feature</Card.Description>
			</Card.Header>
			<Card.Content>
				<div class="space-y-4">
					<p class="text-muted-foreground">
						Upgrade to Pro to access comprehensive audit logs that track all activities in your
						account, including:
					</p>
					<ul class="text-muted-foreground list-inside list-disc space-y-2">
						<li>Secret creation, editing, and deletion</li>
						<li>Check-in activity</li>
						<li>Recipient management</li>
						<li>Login events</li>
						<li>Subscription changes</li>
						<li>Settings updates</li>
					</ul>
					<div class="flex gap-4 pt-4">
						<Button href="/pricing">Upgrade to Pro</Button>
						<Button variant="outline" href="/dashboard">Back to Dashboard</Button>
					</div>
				</div>
			</Card.Content>
		</Card.Root>
	{:else}
		<AuditLogsPage />
	{/if}
</div>
