// frontend/src/app/(authenticated)/secrets/[id]/edit/page.tsx
import { EditSecretForm } from "@/components/forms/editSecretForm"
import { authConfig } from "@/lib/auth-config"
import { getSecret } from "@/lib/db/operations"
import type { Session } from "next-auth"
import { getServerSession } from "next-auth/next"
import { notFound, redirect } from "next/navigation"

interface EditSecretPageProps {
  params: Promise<{ id: string }>
}

export default async function EditSecretPage({ params }: EditSecretPageProps) {
  const { id } = await params
  const session = (await getServerSession(authConfig)) as Session | null

  if (!session?.user?.id) {
    redirect("/auth/signin")
  }

  // Get secret using our database operations
  try {
    const secret = await getSecret(id, session.user.id)
    if (!secret) {
      notFound()
    }

    const initialData = {
      title: secret.title,
      recipients:
        secret.recipients.length > 0
          ? secret.recipients.map((r) => ({
              name: r.name,
              email: r.email || "",
              phone: r.phone || "",
            }))
          : [
              {
                name: "",
                email: "",
                phone: "",
              },
            ],
      check_in_days: secret.checkInDays,
    }

    return (
      <div className="mx-auto max-w-3xl py-8 sm:px-4">
        <h1 className="mb-8 text-left text-2xl font-bold">Edit Secret</h1>
        <EditSecretForm initialData={initialData} secretId={secret.id} />
      </div>
    )
  } catch {
    notFound()
  }
}

// frontend-svelte/src/routes/(authenticated)/secrets/[id]/edit/+page.svelte
<script lang="ts">
	import EditSecretForm from '$lib/components/EditSecretForm.svelte';

	let { data } = $props();
</script>

<svelte:head>
	<title>Edit Secret - KeyFate</title>
</svelte:head>

<div class="mx-auto max-w-3xl py-8 sm:px-4">
	<h1 class="mb-8 text-left text-2xl font-bold">Edit Secret</h1>
	<EditSecretForm initialData={data.initialData} secretId={data.secretId} />
</div>
