// frontend-svelte/src/lib/components/SecretDetailsForm.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import * as Alert from '$lib/components/ui/alert';
  import { Badge } from '$lib/components/ui/badge';
  import { Button } from '$lib/components/ui/button';
  import * as Card from '$lib/components/ui/card';
  import * as Dialog from '$lib/components/ui/dialog';
  import { Separator } from '$lib/components/ui/separator';
  import { Textarea } from '$lib/components/ui/textarea';
  import { toast } from 'svelte-sonner';
  import {
    AlertCircle,
    AlertTriangle,
    Calendar,
    Clock,
    Eye,
    Mail,
    Phone,
    Shield,
    Trash2,
    User
  } from '@lucide/svelte';
  import { format } from 'timeago.js';

  interface SecretRecipient {
    id: string;
    name: string;
    email: string | null;
    phone: string | null;
  }

  interface SecretData {
    id: string;
    title: string;
    recipients: SecretRecipient[];
    check_in_days: number;
    last_check_in: string | null;
    next_check_in: string | null;
    status: 'active' | 'paused' | 'triggered';
    sss_shares_total: number;
    sss_threshold: number;
    server_share: string | null;
    created_at: string;
    updated_at: string;
  }

  let { secret }: { secret: SecretData } = $props();

  let loading = $state(false);
  let error = $state<string | null>(null);
  let serverShare = $state<string | null>(null);
  let showDeleteDialog = $state(false);
  let showRevealDialog = $state(false);
  let serverShareDeleted = $state(!secret.server_share);

  async function handleRevealServerShare() {
    loading = true;
    error = null;

    try {
      const csrfRes = await fetch('/api/csrf-token');
      const { token: csrfToken } = await csrfRes.json();

      const response = await fetch(`/api/secrets/${secret.id}/reveal-server-share`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrfToken }
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to reveal server share');
      }

      const { serverShare: share } = await response.json();
      serverShare = share;
      showRevealDialog = false;
    } catch (err) {
      console.error('Error revealing server share:', err);
      error = err instanceof Error ? err.message : 'Failed to reveal server share';
    } finally {
      loading = false;
    }
  }

  async function handleDeleteServerShare() {
    loading = true;
    error = null;

    try {
      const csrfRes = await fetch('/api/csrf-token');
      const { token: csrfToken } = await csrfRes.json();

      const response = await fetch(`/api/secrets/${secret.id}/delete-server-share`, {
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json', 'x-csrf-token': csrfToken }
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Failed to delete server share');
      }

      serverShareDeleted = true;
      showDeleteDialog = false;
    } catch (err) {
      console.error('Error deleting server share:', err);
      error = err instanceof Error ? err.message : 'Failed to delete server share';
    } finally {
      loading = false;
    }
  }

  function copyToClipboard(text: string) {
    navigator.clipboard.writeText(text);
    toast.success('Copied to clipboard');
  }
</script>

<div class="space-y-6">
  {#if error}
    <Alert.Root variant="destructive">
      <AlertCircle class="h-4 w-4" />
      <Alert.Description>{error}</Alert.Description>
    </Alert.Root>
  {/if}

  {#if serverShareDeleted}
    <Alert.Root variant="destructive">
      <AlertTriangle class="h-4 w-4" />
      <Alert.Description>
        <strong>Secret Disabled:</strong> The server share has been deleted and this secret has been
        automatically paused. No reminder emails will be sent.
      </Alert.Description>
    </Alert.Root>
  {/if}

  <Card.Root>
    <Card.Header>
      <div class="flex items-center justify-between">
        <Card.Title class="text-xl">{secret.title}</Card.Title>
        <Badge variant={secret.status === 'active' ? 'default' : 'secondary'}>
          {secret.status}
        </Badge>
      </div>
    </Card.Header>
    <Card.Content class="space-y-6">
      <!-- SSS Info -->
      <div class="bg-muted/50 rounded-lg p-4">
        <h3 class="mb-3 flex items-center font-medium">
          <Shield class="mr-2 h-4 w-4" />
          Secret Configuration
        </h3>
        <div class="grid grid-cols-2 gap-4 text-sm">
          <div>
            <span class="text-muted-foreground">Total Shares:</span>
            <span class="ml-2 font-medium">{secret.sss_shares_total}</span>
          </div>
          <div>
            <span class="text-muted-foreground">Threshold:</span>
            <span class="ml-2 font-medium">{secret.sss_threshold}</span>
          </div>
        </div>
        <p class="text-muted-foreground mt-2 text-xs">
          Your secret was split into {secret.sss_shares_total} shares. Any {secret.sss_threshold} shares
          can reconstruct the original secret.
        </p>
      </div>

      <Separator />

      <!-- Recipients -->
      <div>
        <h3 class="mb-3 flex items-center font-medium">
          <User class="mr-2 h-4 w-4" />
          Recipients ({secret.recipients.length})
        </h3>
        <div class="space-y-4">
          {#each secret.recipients as recipient}
            <div class="rounded-lg border p-3 text-sm">
              <div class="mb-2 flex items-center">
                <User class="text-muted-foreground mr-2 h-4 w-4" />
                <span class="font-medium">{recipient.name}</span>
              </div>
              <div class="space-y-1 pl-6">
                {#if recipient.email}
                  <div class="flex items-center">
                    <Mail class="text-muted-foreground mr-2 h-3 w-3" />
                    <span class="text-xs">{recipient.email}</span>
                  </div>
                {/if}
                {#if recipient.phone}
                  <div class="flex items-center">
                    <Phone class="text-muted-foreground mr-2 h-3 w-3" />
                    <span class="text-xs">{recipient.phone}</span>
                  </div>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      </div>

      <Separator />

      <!-- Check-in Info -->
      <div>
        <h3 class="mb-3 flex items-center font-medium">
          <Clock class="mr-2 h-4 w-4" />
          Check-in Schedule
        </h3>
        <div class="space-y-2 text-sm">
          <div>
            <span class="text-muted-foreground">Frequency:</span>
            <span class="ml-2 font-medium">Every {secret.check_in_days} days</span>
          </div>
          {#if secret.last_check_in}
            <div>
              <span class="text-muted-foreground">Last check-in:</span>
              <span class="ml-2">{format(secret.last_check_in)}</span>
            </div>
          {/if}
          {#if secret.next_check_in}
            <div>
              <span class="text-muted-foreground">Next check-in due:</span>
              <span class="ml-2">{format(secret.next_check_in)}</span>
            </div>
          {/if}
        </div>
      </div>

      <Separator />

      <!-- Server Share Management -->
      <div>
        <h3 class="mb-3 flex items-center font-medium">
          <Shield class="mr-2 h-4 w-4" />
          Server Share Management
        </h3>

        {#if !serverShareDeleted}
          <div class="space-y-4">
            <p class="text-muted-foreground text-sm">
              The server holds one of your {secret.sss_shares_total} shares.
            </p>
            <div class="flex flex-col gap-2 sm:flex-row">
              <Dialog.Root bind:open={showRevealDialog}>
                <Dialog.Trigger>
                  {#snippet child({ props })}
                    <Button variant="outline" class="flex-1" {...props}>
                      <Eye class="mr-2 h-4 w-4" />
                      Reveal Server Share
                    </Button>
                  {/snippet}
                </Dialog.Trigger>
                <Dialog.Content>
                  <Dialog.Header>
                    <Dialog.Title>Reveal Server Share</Dialog.Title>
                    <Dialog.Description>
                      This will decrypt and show you the server's share.
                    </Dialog.Description>
                  </Dialog.Header>
                  <Alert.Root variant="destructive">
                    <AlertTriangle class="h-4 w-4" />
                    <Alert.Description>
                      <strong>Warning:</strong> Once revealed, this share can be combined with
                      {secret.sss_threshold - 1} other share(s) to reconstruct your secret.
                    </Alert.Description>
                  </Alert.Root>
                  <Dialog.Footer>
                    <Button variant="outline" onclick={() => (showRevealDialog = false)}>
                      Cancel
                    </Button>
                    <Button onclick={handleRevealServerShare} disabled={loading}>
                      {loading ? 'Revealing...' : 'Yes, Reveal Share'}
                    </Button>
                  </Dialog.Footer>
                </Dialog.Content>
              </Dialog.Root>

              <Dialog.Root bind:open={showDeleteDialog}>
                <Dialog.Trigger>
                  {#snippet child({ props })}
                    <Button variant="destructive" class="flex-1" {...props}>
                      <Trash2 class="mr-2 h-4 w-4" />
                      Delete Server Share
                    </Button>
                  {/snippet}
                </Dialog.Trigger>
                <Dialog.Content>
                  <Dialog.Header>
                    <Dialog.Title>Delete Server Share</Dialog.Title>
                    <Dialog.Description>
                      This will permanently delete the server's share.
                    </Dialog.Description>
                  </Dialog.Header>
                  <Alert.Root variant="destructive">
                    <AlertTriangle class="h-4 w-4" />
                    <Alert.Description>
                      <strong>Warning:</strong> After deletion, the server will no longer be able to
                      provide its share to recipients.
                    </Alert.Description>
                  </Alert.Root>
                  <Dialog.Footer>
                    <Button variant="outline" onclick={() => (showDeleteDialog = false)}>
                      Cancel
                    </Button>
                    <Button variant="destructive" onclick={handleDeleteServerShare} disabled={loading}>
                      {loading ? 'Deleting...' : 'Yes, Delete Share'}
                    </Button>
                  </Dialog.Footer>
                </Dialog.Content>
              </Dialog.Root>
            </div>
          </div>
        {:else}
          <Alert.Root>
            <AlertTriangle class="h-4 w-4" />
            <Alert.Description>
              Server share has been deleted. The server can no longer provide its share.
            </Alert.Description>
          </Alert.Root>
        {/if}
      </div>

      <!-- Revealed Server Share -->
      {#if serverShare}
        <div>
          <h3 class="text-destructive mb-3 flex items-center font-medium">
            <Eye class="mr-2 h-4 w-4" />
            Revealed Server Share
          </h3>
          <div class="space-y-2">
            <Textarea value={serverShare} readonly class="font-mono text-xs" rows={3} />
            <Button variant="outline" size="sm" onclick={() => copyToClipboard(serverShare!)}>
              Copy Share
            </Button>
          </div>
        </div>
      {/if}

      <Separator />

      <div class="text-muted-foreground text-xs">
        <div class="flex items-center">
          <Calendar class="mr-2 h-3 w-3" />
          Created {format(secret.created_at)}
        </div>
      </div>
    </Card.Content>
  </Card.Root>

  <div class="flex justify-end space-x-4">
    <Button variant="outline" onclick={() => goto('/dashboard')}>Back to Dashboard</Button>
  </div>
</div>

// frontend/src/components/forms/secretDetailsForm.tsx
"use client"

import { Alert, AlertDescription } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Separator } from "@/components/ui/separator"
import { Textarea } from "@/components/ui/textarea"
import {
  AlertCircle,
  AlertTriangle,
  Calendar,
  Clock,
  Eye,
  Mail,
  Phone,
  Shield,
  Trash2,
  User,
} from "lucide-react"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { format } from "timeago.js"

interface SecretRecipient {
  id: string
  name: string
  email: string | null
  phone: string | null
}

interface Secret {
  id: string
  title: string
  recipients: SecretRecipient[]
  check_in_days: number
  last_check_in: string | null
  next_check_in: string | null
  status: "active" | "paused" | "triggered"
  sss_shares_total: number
  sss_threshold: number
  server_share: string | null
  created_at: string
  updated_at: string
}

interface SecretDetailsFormProps {
  secret: Secret
}

export function SecretDetailsForm({ secret }: SecretDetailsFormProps) {
  const router = useRouter()
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [serverShare, setServerShare] = useState<string | null>(null)
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [showRevealDialog, setShowRevealDialog] = useState(false)
  const [serverShareDeleted, setServerShareDeleted] = useState(
    !secret.server_share,
  )

  const handleRevealServerShare = async () => {
    setLoading(true)
    setError(null)

    try {
      const response = await fetch(
        `/api/secrets/${secret.id}/reveal-server-share`,
        {
          method: "POST",
          headers: { "Content-Type": "application/json" },
        },
      )

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || "Failed to reveal server share")
      }

      const { serverShare: share } = await response.json()
      setServerShare(share)
      setShowRevealDialog(false)
    } catch (error) {
      console.error("Error revealing server share:", error)
      setError(
        error instanceof Error
          ? error.message
          : "Failed to reveal server share",
      )
    } finally {
      setLoading(false)
    }
  }

  const handleDeleteServerShare = async () => {
    setLoading(true)
    setError(null)

    try {
      const response = await fetch(
        `/api/secrets/${secret.id}/delete-server-share`,
        {
          method: "DELETE",
          headers: { "Content-Type": "application/json" },
        },
      )

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || "Failed to delete server share")
      }

      setServerShareDeleted(true)
      setShowDeleteDialog(false)
    } catch (error) {
      console.error("Error deleting server share:", error)
      setError(
        error instanceof Error
          ? error.message
          : "Failed to delete server share",
      )
    } finally {
      setLoading(false)
    }
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
  }

  return (
    <div className="space-y-6">
      {error && (
        <Alert variant="destructive">
          <AlertCircle className="h-4 w-4" />
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {serverShareDeleted && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertDescription>
            <strong>Secret Disabled:</strong> The server share has been deleted
            and this secret has been automatically paused. No reminder emails
            will be sent. The secret serves only as a record of what was created
            and to whom it was sent. The other shares can still be used to
            reconstruct the secret if needed.
          </AlertDescription>
        </Alert>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle className="text-xl">{secret.title}</CardTitle>
            <Badge
              variant={secret.status === "active" ? "default" : "secondary"}
            >
              {secret.status}
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Shamir's Secret Sharing Info */}
          <div className="bg-muted/50 rounded-lg p-4">
            <h3 className="mb-3 flex items-center font-medium">
              <Shield className="mr-2 h-4 w-4" />
              Secret Configuration
            </h3>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-muted-foreground">Total Shares:</span>
                <span className="ml-2 font-medium">
                  {secret.sss_shares_total}
                </span>
              </div>
              <div>
                <span className="text-muted-foreground">Threshold:</span>
                <span className="ml-2 font-medium">{secret.sss_threshold}</span>
              </div>
            </div>
            <p className="text-muted-foreground mt-2 text-xs">
              Your secret was split into {secret.sss_shares_total} shares. Any{" "}
              {secret.sss_threshold} shares can reconstruct the original secret.
            </p>
          </div>

          <Separator />

          {/* Recipient Information */}
          <div>
            <h3 className="mb-3 flex items-center font-medium">
              <User className="mr-2 h-4 w-4" />
              Recipients ({secret.recipients.length})
            </h3>
            <div className="space-y-4">
              {secret.recipients.map((recipient, index) => (
                <div
                  key={recipient.id}
                  className="rounded-lg border p-3 text-sm"
                >
                  <div className="mb-2 flex items-center">
                    <User className="text-muted-foreground mr-2 h-4 w-4" />
                    <span className="font-medium">{recipient.name}</span>
                  </div>
                  <div className="space-y-1 pl-6">
                    {recipient.email && (
                      <div className="flex items-center">
                        <Mail className="text-muted-foreground mr-2 h-3 w-3" />
                        <span className="text-xs">{recipient.email}</span>
                      </div>
                    )}
                    {recipient.phone && (
                      <div className="flex items-center">
                        <Phone className="text-muted-foreground mr-2 h-3 w-3" />
                        <span className="text-xs">{recipient.phone}</span>
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          <Separator />

          {/* Check-in Information */}
          <div>
            <h3 className="mb-3 flex items-center font-medium">
              <Clock className="mr-2 h-4 w-4" />
              Check-in Schedule
            </h3>
            <div className="space-y-2 text-sm">
              <div>
                <span className="text-muted-foreground">Frequency:</span>
                <span className="ml-2 font-medium">
                  Every {secret.check_in_days} days
                </span>
              </div>
              {secret.last_check_in && (
                <div>
                  <span className="text-muted-foreground">Last check-in:</span>
                  <span className="ml-2">{format(secret.last_check_in)}</span>
                </div>
              )}
              {secret.next_check_in && (
                <div>
                  <span className="text-muted-foreground">
                    Next check-in due:
                  </span>
                  <span className="ml-2">{format(secret.next_check_in)}</span>
                </div>
              )}
            </div>
          </div>

          <Separator />

          {/* Server Share Management */}
          <div>
            <h3 className="mb-3 flex items-center font-medium">
              <Shield className="mr-2 h-4 w-4" />
              Server Share Management
            </h3>

            {!serverShareDeleted ? (
              <div className="space-y-4">
                <p className="text-muted-foreground text-sm">
                  The server holds one of your {secret.sss_shares_total} shares.
                  You can reveal it for recovery purposes or delete it for
                  additional security.
                </p>

                <div className="flex flex-col gap-2 sm:flex-row">
                  <Dialog
                    open={showRevealDialog}
                    onOpenChange={setShowRevealDialog}
                  >
                    <DialogTrigger asChild>
                      <Button variant="outline" className="flex-1">
                        <Eye className="mr-2 h-4 w-4" />
                        Reveal Server Share
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Reveal Server Share</DialogTitle>
                        <DialogDescription>
                          This will decrypt and show you the server's share.
                          Only do this if you need it for recovery purposes.
                          This share can be combined with other shares to reveal
                          your secret.
                        </DialogDescription>
                      </DialogHeader>
                      <Alert variant="destructive">
                        <AlertTriangle className="h-4 w-4" />
                        <AlertDescription>
                          <strong>Warning:</strong> Once revealed, this share
                          can be combined with {secret.sss_threshold - 1} other
                          share(s) to reconstruct your secret. Only proceed if
                          you're doing this for legitimate recovery reasons.
                        </AlertDescription>
                      </Alert>
                      <DialogFooter>
                        <Button
                          variant="outline"
                          onClick={() => setShowRevealDialog(false)}
                        >
                          Cancel
                        </Button>
                        <Button
                          onClick={handleRevealServerShare}
                          disabled={loading}
                        >
                          {loading ? "Revealing..." : "Yes, Reveal Share"}
                        </Button>
                      </DialogFooter>
                    </DialogContent>
                  </Dialog>

                  <Dialog
                    open={showDeleteDialog}
                    onOpenChange={setShowDeleteDialog}
                  >
                    <DialogTrigger asChild>
                      <Button variant="destructive" className="flex-1">
                        <Trash2 className="mr-2 h-4 w-4" />
                        Delete Server Share
                      </Button>
                    </DialogTrigger>
                    <DialogContent>
                      <DialogHeader>
                        <DialogTitle>Delete Server Share</DialogTitle>
                        <DialogDescription>
                          This will permanently delete the server's share. The
                          other shares can still be used to reconstruct the
                          secret.
                        </DialogDescription>
                      </DialogHeader>
                      <Alert variant="destructive">
                        <AlertTriangle className="h-4 w-4" />
                        <AlertDescription>
                          <strong>Warning:</strong> After deletion, the server
                          will no longer be able to provide its share to
                          recipients. However, if you or recipients have{" "}
                          {secret.sss_threshold} shares, the secret can still be
                          reconstructed.
                        </AlertDescription>
                      </Alert>
                      <DialogFooter>
                        <Button
                          variant="outline"
                          onClick={() => setShowDeleteDialog(false)}
                        >
                          Cancel
                        </Button>
                        <Button
                          variant="destructive"
                          onClick={handleDeleteServerShare}
                          disabled={loading}
                        >
                          {loading ? "Deleting..." : "Yes, Delete Share"}
                        </Button>
                      </DialogFooter>
                    </DialogContent>
                  </Dialog>
                </div>
              </div>
            ) : (
              <Alert>
                <AlertTriangle className="h-4 w-4" />
                <AlertDescription>
                  Server share has been deleted. The server can no longer
                  provide its share to recipients.
                </AlertDescription>
              </Alert>
            )}
          </div>

          {/* Revealed Server Share */}
          {serverShare && (
            <div>
              <h3 className="text-destructive mb-3 flex items-center font-medium">
                <Eye className="mr-2 h-4 w-4" />
                Revealed Server Share
              </h3>
              <Alert variant="destructive" className="mb-3">
                <AlertTriangle className="h-4 w-4" />
                <AlertDescription>
                  This is your server's share. Keep it secure and only use it
                  for legitimate recovery purposes.
                </AlertDescription>
              </Alert>
              <div className="space-y-2">
                <Textarea
                  value={serverShare}
                  readOnly
                  className="font-mono text-xs"
                  rows={3}
                />
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => {
                    copyToClipboard(serverShare)
                    const button = document.activeElement as HTMLButtonElement
                    const originalText = button.textContent
                    button.textContent = "Copied!"
                    setTimeout(() => {
                      button.textContent = originalText
                    }, 2000)
                  }}
                >
                  Copy Share
                </Button>
              </div>
            </div>
          )}

          <Separator />

          {/* Metadata */}
          <div className="text-muted-foreground text-xs">
            <div className="flex items-center">
              <Calendar className="mr-2 h-3 w-3" />
              Created {format(secret.created_at)}
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="flex justify-end space-x-4">
        <Button variant="outline" onClick={() => router.push("/dashboard")}>
          Back to Dashboard
        </Button>
      </div>
    </div>
  )
}
