// frontend/src/routes/(authenticated)/settings/general/+page.svelte
<script lang="ts">
  let { data } = $props();
</script>

<svelte:head>
  <title>General Settings - KeyFate</title>
</svelte:head>

<div class="space-y-8">
  <div>
    <h2 class="font-space text-xl font-bold tracking-tight">General Settings</h2>
    <p class="text-sm text-muted-foreground mt-1">View your account information</p>
  </div>

  <div class="space-y-6">
    <div>
      <span class="text-xs text-muted-foreground font-medium">Name</span>
      <p class="text-base text-foreground mt-1">{data.user.name}</p>
    </div>
    <div>
      <span class="text-xs text-muted-foreground font-medium">Email</span>
      <p class="text-base text-foreground mt-1">{data.user.email}</p>
    </div>
    <div>
      <span class="text-xs text-muted-foreground font-medium">Joined</span>
      <p class="text-base text-foreground mt-1">{data.user.joinDate}</p>
    </div>
  </div>
</div>

// frontend/src/app/(authenticated)/settings/general/page.tsx
import type { Session } from "next-auth"
import { authConfig } from "@/lib/auth-config"
import { getServerSession } from "next-auth/next"
import { redirect } from "next/navigation"
import { getDatabase } from "@/lib/db/drizzle"
import { users } from "@/lib/db/schema"
import { eq } from "drizzle-orm"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { SettingsPageHeader } from "@/components/settings/SettingsPageHeader"

export default async function GeneralSettingsPage() {
  const session = (await getServerSession(authConfig)) as Session | null

  if (!session?.user?.id) {
    redirect("/sign-in")
  }

  const userId = session.user.id
  const db = await getDatabase()

  const [user] = await db
    .select()
    .from(users)
    .where(eq(users.id, userId))
    .limit(1)

  const joinDate = user?.createdAt
    ? new Date(user.createdAt).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      })
    : "Unknown"

  return (
    <div className="space-y-6">
      <SettingsPageHeader
        title="General Settings"
        description="View your account information"
      />

      <Card>
        <CardHeader>
          <CardTitle>Account Information</CardTitle>
          <CardDescription>Your KeyFate account details</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div>
            <label className="text-muted-foreground text-sm font-medium">
              Name
            </label>
            <p className="text-lg">{user?.name || "Not set"}</p>
          </div>
          <div>
            <label className="text-muted-foreground text-sm font-medium">
              Email
            </label>
            <p className="text-lg">{user?.email}</p>
          </div>
          <div>
            <label className="text-muted-foreground text-sm font-medium">
              Joined
            </label>
            <p className="text-lg">{joinDate}</p>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
