// frontend-svelte/src/lib/components/EmailVerification.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import { page } from '$app/stores';
  import * as Alert from '$lib/components/ui/alert';
  import { Badge } from '$lib/components/ui/badge';
  import { Button } from '$lib/components/ui/button';
  import * as Card from '$lib/components/ui/card';
  import { Separator } from '$lib/components/ui/separator';
  import OtpInput from '$lib/components/OtpInput.svelte';
  import ResendButton from '$lib/components/ResendButton.svelte';
  import { toast } from 'svelte-sonner';
  import {
    AlertCircle,
    ArrowLeft,
    CheckCircle2,
    Clock,
    Loader2,
    Mail
  } from '@lucide/svelte';

  let {
    email: emailProp = '',
    showOTPInput = true,
    callbackUrl: callbackUrlProp = '/dashboard',
    class: className
  }: {
    email?: string;
    showOTPInput?: boolean;
    callbackUrl?: string;
    class?: string;
  } = $props();

  let verificationStatus = $state<'unverified' | 'pending' | 'verified' | 'error'>('unverified');
  let error = $state<string | null>(null);
  let isVerifyingOTP = $state(false);
  let loading = $state(true);
  let success = $state(false);
  let alreadyVerified = $state(false);

  const searchParams = $derived($page.url.searchParams);
  const email = $derived(emailProp || searchParams.get('email') || $page.data.session?.user?.email || '');
  const callbackUrl = $derived(callbackUrlProp || searchParams.get('callbackUrl') || '/dashboard');
  const token = $derived(searchParams.get('token'));

  $effect(() => {
    const session = $page.data.session;
    if (!session?.user) {
      loading = false;
      return;
    }

    // Check if already verified
    if ((session.user as any)?.emailVerified) {
      alreadyVerified = true;
      loading = false;
      setTimeout(() => goto(callbackUrl), 2000);
      return;
    }

    // If token present, verify automatically
    if (token && email) {
      handleTokenVerification(token, email);
    } else {
      loading = false;
    }
  });

  async function handleTokenVerification(verificationToken: string, emailAddress: string) {
    loading = true;
    error = null;

    try {
      const response = await fetch('/api/auth/verify-email-nextauth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token: verificationToken, email: emailAddress })
      });

      const result = await response.json();

      if (result.success) {
        success = true;
        verificationStatus = 'verified';
        toast.success('Your email address has been successfully verified.');
        setTimeout(() => goto(callbackUrl), 2000);
      } else {
        error = result.error || 'Verification failed';
        verificationStatus = 'error';
      }
    } catch (err) {
      console.error('Verification error:', err);
      error = 'Network error. Please try again.';
      verificationStatus = 'error';
    } finally {
      loading = false;
    }
  }

  async function handleOTPComplete(otp: string) {
    if (!email || otp.length < 6) return;

    isVerifyingOTP = true;
    error = null;

    try {
      const response = await fetch('/api/auth/verify-email-nextauth', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, otp })
      });

      const result = await response.json();

      if (result.success) {
        success = true;
        verificationStatus = 'verified';
        toast.success('Your email address has been successfully verified.');
        setTimeout(() => goto(callbackUrl), 1500);
      } else {
        error = result.error || 'Invalid verification code';
        verificationStatus = 'error';
      }
    } catch (err) {
      console.error('OTP verification error:', err);
      error = 'Network error. Please try again.';
      verificationStatus = 'error';
    } finally {
      isVerifyingOTP = false;
    }
  }

  function handleOTPChange(_otp: string) {
    if (error) error = null;
  }

  async function handleResendEmail() {
    error = null;
    verificationStatus = 'pending';
  }
</script>

{#if loading}
  <div class="flex min-h-screen items-center justify-center">
    <div class="flex items-center space-x-2">
      <Loader2 class="h-4 w-4 animate-spin" data-testid="loading-spinner" />
      <span>Checking verification status...</span>
    </div>
  </div>
{:else if alreadyVerified || success}
  <div class="flex min-h-screen items-center justify-center {className ?? ''}">
    <Card.Root class="w-full max-w-md" data-testid="verification-success-card">
      <Card.Content class="pt-6">
        <div class="space-y-4 text-center">
          <CheckCircle2 class="text-accent-foreground mx-auto h-16 w-16" />
          <div>
            <h3 class="text-accent-foreground text-lg font-semibold">
              {alreadyVerified ? 'Email Already Verified' : 'Email Verified!'}
            </h3>
            <p class="text-muted-foreground text-sm">Redirecting...</p>
          </div>
        </div>
      </Card.Content>
    </Card.Root>
  </div>
{:else}
  <div
    data-testid="verification-container"
    class="bg-secondary flex min-h-screen items-center justify-center px-4 py-16 {className ?? ''}"
  >
    <Card.Root class="w-full max-w-md" data-testid="verification-card">
      <Card.Header class="text-center">
        <div
          class="bg-muted mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full"
        >
          <Mail class="text-muted-foreground h-6 w-6" />
        </div>
        <Card.Title class="text-2xl font-bold">Verify your email address</Card.Title>
        <Card.Description>
          We need to verify your email address before you can access the application.
        </Card.Description>
      </Card.Header>

      <Card.Content class="space-y-6">
        <!-- Verification Status -->
        {#if error}
          <Alert.Root variant="destructive" data-testid="verification-error">
            <AlertCircle class="h-4 w-4" />
            <Alert.Description>
              {error}
              {#if error.includes('Network error')}
                <Button
                  variant="link"
                  size="sm"
                  onclick={() => { error = null; }}
                  class="text-destructive hover:text-destructive/80 ml-2 h-auto p-0"
                >
                  Retry
                </Button>
              {/if}
            </Alert.Description>
          </Alert.Root>
        {:else if verificationStatus === 'pending'}
          <Alert.Root class="border-muted bg-muted/50" data-testid="verification-pending">
            <Clock class="text-muted-foreground h-4 w-4" />
            <Alert.Description class="text-muted-foreground">
              Verification in progress for <strong>{email}</strong>...
            </Alert.Description>
          </Alert.Root>
        {:else}
          <div class="space-y-3" data-testid="verification-info">
            <div class="flex items-center gap-2">
              <Mail class="text-muted-foreground h-4 w-4" />
              <span class="text-foreground text-sm">
                Verification email sent to <strong>{email}</strong>
              </span>
              <Badge variant="outline" class="text-xs">Unverified</Badge>
            </div>
          </div>
        {/if}

        <!-- OTP Input Section -->
        {#if showOTPInput}
          <Separator />
          <div class="space-y-4">
            <div class="text-center">
              <p class="text-muted-foreground text-sm">
                Enter the 8-digit code sent to <span class="font-medium">{email}</span>
              </p>
            </div>

            <OtpInput
              onComplete={handleOTPComplete}
              onChange={handleOTPChange}
              disabled={isVerifyingOTP}
            />

            {#if isVerifyingOTP}
              <div class="text-muted-foreground flex items-center justify-center space-x-2 text-sm">
                <Loader2 class="h-4 w-4 animate-spin" data-testid="loading-spinner" />
                <span>Verifying...</span>
              </div>
            {/if}
          </div>
        {/if}

        <!-- Action Buttons -->
        <div class="space-y-4">
          <ResendButton
            {email}
            onResend={handleResendEmail}
            disabled={verificationStatus === 'pending'}
          />

          <div class="text-center">
            <p class="text-muted-foreground mb-3 text-xs">
              Didn't receive the email? Check your spam folder.
            </p>
          </div>
        </div>

        <!-- Navigation -->
        <div class="space-y-3 border-t pt-4">
          <Button onclick={() => goto(callbackUrl)} class="w-full" variant="default">
            Continue
          </Button>

          <Button
            onclick={() => goto('/sign-in')}
            variant="ghost"
            class="text-muted-foreground w-full"
          >
            <ArrowLeft class="mr-2 h-4 w-4" />
            Back to sign in
          </Button>
        </div>
      </Card.Content>
    </Card.Root>
  </div>
{/if}

// frontend/src/components/auth/email-verification.tsx
"use client"

import { Alert, AlertDescription } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { useToast } from "@/hooks/use-toast"
import {
  getEmailVerificationStatus,
  resendVerificationEmail,
  verifyEmailWithOTP,
  type EmailVerificationResult,
  type EmailVerificationStatus,
} from "@/lib/email-verification"
import { CheckCircle2, Clock, Loader2, Mail, XCircle } from "lucide-react"
import { useCallback, useEffect, useState } from "react"

interface OTPVerificationFormProps {
  email: string
  onSuccess: (result: EmailVerificationResult) => void
  onError: (error: string) => void
}

export function OTPVerificationForm({
  email,
  onSuccess,
  onError,
}: OTPVerificationFormProps) {
  const [otp, setOtp] = useState("")
  const [loading, setLoading] = useState(false)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()

    if (otp.length !== 6) {
      onError("Please enter a valid 8-digit code")
      return
    }

    setLoading(true)
    try {
      const result = await verifyEmailWithOTP(email, otp)

      if (result.success) {
        onSuccess(result)
      } else {
        onError(result.error || "Verification failed")
      }
    } catch {
      onError("An unexpected error occurred")
    } finally {
      setLoading(false)
    }
  }

  const handleOtpChange = (value: string) => {
    // Only allow numbers and limit to 6 digits
    const numericValue = value.replace(/\D/g, "").slice(0, 6)
    setOtp(numericValue)
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="space-y-2">
        <Label htmlFor="otp">Enter verification code</Label>
        <Input
          id="otp"
          name="otp"
          type="text"
          inputMode="numeric"
          placeholder="123456"
          value={otp}
          onChange={(e) => handleOtpChange(e.target.value)}
          disabled={loading}
          maxLength={6}
          className="text-center font-mono text-lg tracking-widest"
        />
        <p className="text-muted-foreground text-sm">
          Enter the 8-digit code sent to {email}
        </p>
      </div>

      <Button
        type="submit"
        disabled={loading || otp.length !== 6}
        className="w-full"
      >
        {loading ? (
          <>
            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            Verifying...
          </>
        ) : (
          "Verify Email"
        )}
      </Button>
    </form>
  )
}

interface EmailVerificationStatusProps {
  showIcon?: boolean
}

export function EmailVerificationStatus({
  showIcon = true,
}: EmailVerificationStatusProps) {
  const [status, setStatus] = useState<EmailVerificationStatus | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const checkStatus = async () => {
      try {
        const result = await getEmailVerificationStatus()
        setStatus(result)
      } finally {
        setLoading(false)
      }
    }

    checkStatus()
  }, [])

  if (loading) {
    return (
      <div
        className="flex items-center space-x-2"
        data-testid="loading-spinner"
      >
        <Loader2 className="h-4 w-4 animate-spin" />
        <span>Checking verification status...</span>
      </div>
    )
  }

  if (!status) {
    return null
  }

  return (
    <div className="flex items-center space-x-2">
      {showIcon &&
        (status.isVerified ? (
          <CheckCircle2
            className="text-accent-foreground h-4 w-4"
            data-testid="verified-icon"
          />
        ) : (
          <XCircle
            className="text-muted-foreground h-4 w-4"
            data-testid="unverified-icon"
          />
        ))}
      <span
        className={
          status.isVerified ? "text-accent-foreground" : "text-muted-foreground"
        }
      >
        {status.isVerified ? "Email verified" : "Email not verified"}
      </span>
    </div>
  )
}

interface ResendVerificationButtonProps {
  email: string
  onSuccess?: () => void
  onError?: (error: string) => void
  cooldownSeconds?: number
}

export function ResendVerificationButton({
  email,
  onSuccess,
  onError,
  cooldownSeconds = 60,
}: ResendVerificationButtonProps) {
  const [loading, setLoading] = useState(false)
  const [cooldown, setCooldown] = useState(0)
  const { toast } = useToast()

  useEffect(() => {
    if (cooldown > 0) {
      const timer = setTimeout(() => setCooldown((c) => c - 1), 1000)
      return () => clearTimeout(timer)
    }
  }, [cooldown])

  const handleResend = async () => {
    setLoading(true)
    try {
      const result = await resendVerificationEmail(email)

      if (result.success) {
        setCooldown(cooldownSeconds)
        toast({
          title: "Email sent",
          description:
            "Verification email has been sent. Please check your inbox.",
        })
        onSuccess?.()
      } else {
        const errorMessage = result.error || "Failed to resend email"
        toast({
          title: "Error",
          description: errorMessage,
          variant: "destructive",
        })
        onError?.(errorMessage)
      }
    } catch {
      const errorMessage = "An unexpected error occurred"
      toast({
        title: "Error",
        description: errorMessage,
        variant: "destructive",
      })
      onError?.(errorMessage)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Button
      type="button"
      variant="ghost"
      size="sm"
      onClick={handleResend}
      disabled={loading || cooldown > 0}
      className="text-sm"
    >
      {loading ? (
        <>
          <Loader2 className="mr-2 h-3 w-3 animate-spin" />
          Sending...
        </>
      ) : cooldown > 0 ? (
        <>
          <Clock className="mr-2 h-3 w-3" />
          Resend in {cooldown}s
        </>
      ) : (
        <>
          <Mail className="mr-2 h-3 w-3" />
          Resend verification email
        </>
      )}
    </Button>
  )
}

interface EmailVerificationPromptProps {
  email: string
  onVerificationComplete: () => void
  onCancel?: () => void
}

export function EmailVerificationPrompt({
  email,
  onVerificationComplete,
  onCancel,
}: EmailVerificationPromptProps) {
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)
  const { toast } = useToast()

  const handleSuccess = useCallback(() => {
    setSuccess(true)
    setError(null)
    toast({
      title: "Email verified!",
      description: "Your email address has been successfully verified.",
    })

    // Brief delay to show success message before completing
    setTimeout(() => {
      onVerificationComplete()
    }, 1500)
  }, [onVerificationComplete, toast])

  const handleError = useCallback((errorMessage: string) => {
    setError(errorMessage)
    setSuccess(false)
  }, [])

  const handleResendSuccess = useCallback(() => {
    setError(null) // Clear any previous errors
  }, [])

  if (success) {
    return (
      <Card>
        <CardContent className="pt-6">
          <div className="space-y-4 text-center">
            <CheckCircle2 className="text-accent-foreground mx-auto h-16 w-16" />
            <div>
              <h3 className="text-accent-foreground text-lg font-semibold">
                Email Verified!
              </h3>
              <p className="text-muted-foreground text-sm">
                Redirecting you to the dashboard...
              </p>
            </div>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card className="mx-auto w-full max-w-md">
      <CardHeader>
        <CardTitle className="flex items-center space-x-2">
          <Mail className="h-5 w-5" />
          <span>Verify your email address</span>
        </CardTitle>
        <CardDescription>
          We've sent a verification code to <strong>{email}</strong>
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {error && (
          <Alert variant="destructive">
            <XCircle className="h-4 w-4" />
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        )}

        <OTPVerificationForm
          email={email}
          onSuccess={handleSuccess}
          onError={handleError}
        />

        <div className="space-y-2 text-center">
          <p className="text-muted-foreground text-sm">
            Didn't receive the email? Check your spam folder.
          </p>

          <ResendVerificationButton
            email={email}
            onSuccess={handleResendSuccess}
            onError={handleError}
          />
        </div>

        {onCancel && (
          <div className="border-t pt-4">
            <Button
              type="button"
              variant="ghost"
              onClick={onCancel}
              className="w-full text-sm"
            >
              Back to sign in
            </Button>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
