// frontend/src/components/theme-toggle.tsx
"use client"

import { Button } from "@/components/ui/button"
import { Moon, Sun } from "lucide-react"
import { useTheme } from "next-themes"
import * as React from "react"

export function ThemeToggle() {
  const { theme, setTheme } = useTheme()
  const [mounted, setMounted] = React.useState(false)

  // Prevent hydration mismatch by only rendering after mount
  React.useEffect(() => {
    setMounted(true)
  }, [])

  if (!mounted) {
    // Return a placeholder with the same dimensions to prevent layout shift
    return (
      <Button variant="ghost" size="icon" disabled>
        <div className="h-[1.2rem] w-[1.2rem]" />
        <span className="sr-only">Toggle theme</span>
      </Button>
    )
  }

  return (
    <Button
      variant="ghost"
      size="icon"
      onClick={() => setTheme(theme === "light" ? "dark" : "light")}
    >
      {theme === "light" ? (
        <Moon className="h-[1.2rem] w-[1.2rem]" />
      ) : (
        <Sun className="h-[1.2rem] w-[1.2rem]" />
      )}
      <span className="sr-only">Toggle theme</span>
    </Button>
  )
}

// frontend-svelte/src/lib/components/ThemeToggle.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Moon, Sun } from '@lucide/svelte';
  import { toggleMode, mode } from 'mode-watcher';
</script>

<Button variant="ghost" size="icon" onclick={toggleMode}>
  {#if mode.current === 'dark'}
    <Sun class="h-[1.2rem] w-[1.2rem]" />
  {:else}
    <Moon class="h-[1.2rem] w-[1.2rem]" />
  {/if}
  <span class="sr-only">Toggle theme</span>
</Button>
