// frontend/src/components/toggle-pause-button.tsx
"use client"

import { Button } from "@/components/ui/button"
import { mapApiSecretToDrizzleShape } from "@/lib/db/secret-mapper"
import { Secret } from "@/types"
import { Loader2, PauseIcon, PlayIcon } from "lucide-react"
import { useState } from "react"

interface TogglePauseButtonProps {
  secretId: string
  status: Secret["status"]
  onToggleSuccess: (updatedSecret: Secret) => void
}

export function TogglePauseButton({
  secretId,
  status,
  onToggleSuccess,
}: TogglePauseButtonProps) {
  const [isLoading, setIsLoading] = useState(false)

  const handleTogglePause = async () => {
    try {
      setIsLoading(true)
      const response = await fetch(`/api/secrets/${secretId}/toggle-pause`, {
        method: "POST",
      })

      const data = await response.json()
      if (data.error) throw new Error(data.error)

      // Convert API response (snake_case) to Drizzle format (camelCase)
      const updatedSecret = mapApiSecretToDrizzleShape(data.secret)

      onToggleSuccess(updatedSecret)
    } catch (error) {
      console.error("Error toggling pause:", error)
    } finally {
      setIsLoading(false)
    }
  }

  return (
    <Button
      variant="ghost"
      size="sm"
      onClick={handleTogglePause}
      disabled={isLoading}
    >
      {isLoading ? (
        <>
          <Loader2 className="h-4 w-4 animate-spin" />
          {status === "active" ? "Pause" : "Resume"}
        </>
      ) : (
        <>
          {status === "active" ? (
            <>
              <PauseIcon className="h-4 w-4" />
              Pause
            </>
          ) : (
            <>
              <PlayIcon className="h-4 w-4" />
              Resume
            </>
          )}
        </>
      )}
    </Button>
  )
}

// frontend-svelte/src/lib/components/TogglePauseButton.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import { Loader2, Pause, Play } from '@lucide/svelte';
  import type { Secret } from '$lib/types/secret-types';
  import { mapApiSecretToDrizzleShape } from '$lib/db/secret-mapper';

  let {
    secretId,
    status,
    onToggleSuccess
  }: {
    secretId: string;
    status: Secret['status'];
    onToggleSuccess: (updatedSecret: Secret) => void;
  } = $props();

  let isLoading = $state(false);

  async function handleTogglePause() {
    try {
      isLoading = true;

      const csrfRes = await fetch('/api/csrf-token');
      const { token: csrfToken } = await csrfRes.json();

      const response = await fetch(`/api/secrets/${secretId}/toggle-pause`, {
        method: 'POST',
        headers: {
          'x-csrf-token': csrfToken
        }
      });

      const data = await response.json();
      if (data.error) throw new Error(data.error);

      onToggleSuccess(mapApiSecretToDrizzleShape(data.secret) as Secret);
    } catch (err) {
      console.error('Error toggling pause:', err);
    } finally {
      isLoading = false;
    }
  }
</script>

<Button variant="ghost" size="sm" onclick={handleTogglePause} disabled={isLoading} class="">
  {#if isLoading}
    <Loader2 class="h-4 w-4 animate-spin" />
    {status === 'active' ? 'Pause' : 'Resume'}
  {:else if status === 'active'}
    <Pause class="h-4 w-4" />
    Pause
  {:else}
    <Play class="h-4 w-4" />
    Resume
  {/if}
</Button>
