// frontend/src/components/auth/turnstile.tsx
"use client"

import { Turnstile, TurnstileInstance } from "@marsidev/react-turnstile"
import { useRef, forwardRef, useImperativeHandle, useEffect } from "react"

export interface TurnstileRef {
  reset: () => void
  getToken: () => string | undefined
}

interface TurnstileWidgetProps {
  onSuccess: (token: string) => void
  onError?: () => void
  onExpire?: () => void
}

export const TurnstileWidget = forwardRef<TurnstileRef, TurnstileWidgetProps>(
  function TurnstileWidget({ onSuccess, onError, onExpire }, ref) {
    const turnstileRef = useRef<TurnstileInstance>(null)
    const tokenRef = useRef<string | undefined>(undefined)

    useImperativeHandle(ref, () => ({
      reset: () => {
        tokenRef.current = undefined
        turnstileRef.current?.reset()
      },
      getToken: () => tokenRef.current,
    }))

    const siteKey = process.env.NEXT_PUBLIC_TURNSTILE_SITE_KEY

    // Auto-succeed in development when no site key is configured
    useEffect(() => {
      if (!siteKey && process.env.NODE_ENV === "development") {
        const timeoutId = setTimeout(() => onSuccess("dev-bypass-token"), 100)
        return () => clearTimeout(timeoutId)
      }
    }, [siteKey, onSuccess])

    // In development or if no site key, render nothing (allow form submission)
    if (!siteKey) {
      return null
    }

    return (
      <div className="flex justify-center">
        <Turnstile
          ref={turnstileRef}
          siteKey={siteKey}
          onSuccess={(token) => {
            tokenRef.current = token
            onSuccess(token)
          }}
          onError={() => {
            tokenRef.current = undefined
            onError?.()
          }}
          onExpire={() => {
            tokenRef.current = undefined
            onExpire?.()
          }}
          options={{
            theme: "auto",
            size: "normal",
          }}
        />
      </div>
    )
  }
)

/**
 * Server-side Turnstile token verification
 */
export async function verifyTurnstileToken(token: string): Promise<boolean> {
  const secretKey = process.env.TURNSTILE_SECRET_KEY
  const isDev = process.env.NODE_ENV === "development"

  // Only allow bypass in development when no secret key is configured
  if (isDev && !secretKey) {
    console.warn("[Turnstile] No secret key configured, bypassing in development")
    return true
  }

  // In production, require secret key
  if (!secretKey) {
    console.error("[Turnstile] TURNSTILE_SECRET_KEY not configured")
    return false
  }

  // Never accept dev bypass token in production
  if (token === "dev-bypass-token") {
    return isDev
  }

  try {
    const response = await fetch(
      "https://challenges.cloudflare.com/turnstile/v0/siteverify",
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          secret: secretKey,
          response: token,
        }),
      }
    )

    if (!response.ok) {
      console.error(`[Turnstile] API error: ${response.status}`)
      return false
    }

    const data = await response.json()
    return data.success === true
  } catch (error) {
    console.error("[Turnstile] Verification error:", error)
    return false
  }
}

// frontend-svelte/src/lib/components/Turnstile.svelte
<script lang="ts">
  import { env } from '$env/dynamic/public';
  import { onMount } from 'svelte';

  let {
    onSuccess,
    onError,
    onExpire
  }: {
    onSuccess: (token: string) => void;
    onError?: () => void;
    onExpire?: () => void;
  } = $props();

  let container: HTMLDivElement;
  let widgetId: string | undefined;

  const siteKey = env.PUBLIC_TURNSTILE_SITE_KEY;

  onMount(() => {
    if (!siteKey) {
      // Dev bypass
      const timeoutId = setTimeout(() => onSuccess('dev-bypass-token'), 100);
      return () => clearTimeout(timeoutId);
    }

    // Load Turnstile script if not already loaded
    if (!document.querySelector('script[src*="turnstile"]')) {
      const script = document.createElement('script');
      script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit';
      script.async = true;
      script.onload = renderWidget;
      document.head.appendChild(script);
    } else {
      renderWidget();
    }

    return () => {
      if (widgetId && (window as any).turnstile) {
        (window as any).turnstile.remove(widgetId);
      }
    };
  });

  function renderWidget() {
    if (!siteKey || !container || !(window as any).turnstile) return;

    widgetId = (window as any).turnstile.render(container, {
      sitekey: siteKey,
      callback: (token: string) => onSuccess(token),
      'error-callback': () => onError?.(),
      'expired-callback': () => onExpire?.(),
      theme: 'auto',
      size: 'normal'
    });
  }

  export function reset() {
    if (widgetId && (window as any).turnstile) {
      (window as any).turnstile.reset(widgetId);
    }
  }
</script>

{#if siteKey}
  <div class="flex justify-center">
    <div bind:this={container}></div>
  </div>
{/if}
