// frontend/src/components/subscription/BillingPortalButton.tsx
"use client"

import { Button } from "@/components/ui/button"
import { useCSRF } from "@/hooks/useCSRF"
import { useState } from "react"

export function BillingPortalButton() {
  const { fetchWithCSRF } = useCSRF()
  const [loading, setLoading] = useState(false)

  const handlePortal = async () => {
    setLoading(true)

    try {
      const response = await fetchWithCSRF("/api/create-portal-session", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
      })

      if (response.redirected) {
        window.location.href = response.url
      } else {
        console.error("Portal creation failed")
      }
    } catch (error) {
      console.error("Error:", error)
    } finally {
      setLoading(false)
    }
  }

  return (
    <Button onClick={handlePortal} disabled={loading} variant="outline">
      {loading ? "Loading..." : "Manage Billing"}
    </Button>
  )
}

// frontend/src/lib/components/BillingPortalButton.svelte
<script lang="ts">
	import { Button } from '$lib/components/ui/button';

	let loading = $state(false);

	async function handlePortal() {
		loading = true;

		try {
			const csrfRes = await fetch('/api/csrf-token');
			const { token } = await csrfRes.json();

			const response = await fetch('/api/create-portal-session', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
					'x-csrf-token': token
				}
			});

			if (response.redirected) {
				window.location.href = response.url;
			} else {
				console.error('Portal creation failed');
			}
		} catch (error) {
			console.error('Error:', error);
		} finally {
			loading = false;
		}
	}
</script>

<Button onclick={handlePortal} disabled={loading} variant="outline" class="">
	{loading ? 'Loading...' : 'Manage Billing'}
</Button>
