// frontend/src/components/ExportRecoveryKitButton.tsx
"use client"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import {
  downloadRecoveryKit,
  getUserManagedSharesFromStorage,
  type RecoveryKitData,
  type SecretMetadata,
} from "@/lib/export-recovery-kit"
import { useCSRF } from "@/hooks/useCSRF"
import { AlertCircle, Download, Loader2, ShieldCheck } from "lucide-react"
import { useCallback, useState } from "react"

interface ExportRecoveryKitButtonProps {
  secret: {
    id: string
    title: string
    checkInDays: number
    createdAt: Date | string
    recipients: Array<{
      id: string
      name: string
      email: string | null
      phone: string | null
    }>
  }
  threshold: number
  totalShares: number
  className?: string
}

export function ExportRecoveryKitButton({
  secret,
  threshold,
  totalShares,
  className,
}: ExportRecoveryKitButtonProps) {
  const [isOpen, setIsOpen] = useState(false)
  const [isExporting, setIsExporting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)
  const { fetchWithCSRF } = useCSRF()

  const handleExport = useCallback(async () => {
    setIsExporting(true)
    setError(null)
    setSuccess(false)

    try {
      // Fetch decrypted server share from API (with CSRF token)
      const response = await fetchWithCSRF(`/api/secrets/${secret.id}/export-share`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        credentials: "include",
      })

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}))

        if (response.status === 401) {
          throw new Error("Session expired. Please log in again.")
        }
        if (response.status === 404) {
          throw new Error("Server share not found or has been deleted.")
        }
        throw new Error(errorData.error || "Failed to retrieve server share")
      }

      const shareData = await response.json()
      const serverShare = shareData.serverShare

      // Get user-managed shares from localStorage
      const userManagedShares = getUserManagedSharesFromStorage(secret.id)

      // Build recovery kit data
      const metadata: SecretMetadata = {
        id: secret.id,
        title: secret.title,
        threshold,
        totalShares,
        checkInDays: secret.checkInDays,
        recipients: secret.recipients.map((r) => ({
          name: r.name,
          email: r.email || "",
        })),
        createdAt:
          typeof secret.createdAt === "string"
            ? secret.createdAt
            : secret.createdAt.toISOString(),
        exportedAt: new Date().toISOString(),
      }

      const recoveryKitData: RecoveryKitData = {
        metadata,
        serverShare,
        userManagedShares,
      }

      // Generate and download the recovery kit
      await downloadRecoveryKit(recoveryKitData)

      setSuccess(true)

      // Auto-close after success
      setTimeout(() => {
        setIsOpen(false)
        setSuccess(false)
      }, 2000)
    } catch (err) {
      console.error("Export error:", err)
      setError(err instanceof Error ? err.message : "Failed to export recovery kit")
    } finally {
      setIsExporting(false)
    }
  }, [secret, threshold, totalShares, fetchWithCSRF])

  return (
    <Dialog open={isOpen} onOpenChange={setIsOpen}>
      <DialogTrigger asChild>
        <Button variant="outline" className={className}>
          <Download className="mr-2 h-4 w-4" />
          Export Recovery Kit
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <ShieldCheck className="h-5 w-5 text-primary" />
            Export Recovery Kit
          </DialogTitle>
          <DialogDescription>
            Download a complete backup of your secret that works without KeyFate.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="rounded-lg border bg-muted/50 p-4">
            <h4 className="mb-2 font-medium">This kit includes:</h4>
            <ul className="space-y-1 text-sm text-muted-foreground">
              <li>• Standalone recovery tool (works offline)</li>
              <li>• Server share (decrypted)</li>
              <li>• Your user-managed shares (if available)</li>
              <li>• Secret metadata and instructions</li>
            </ul>
          </div>

          <div className="rounded-lg border border-amber-500/50 bg-amber-500/10 p-4">
            <div className="flex gap-2">
              <AlertCircle className="h-5 w-5 shrink-0 text-amber-500" />
              <div>
                <h4 className="font-medium text-amber-700 dark:text-amber-400">
                  Security Notice
                </h4>
                <p className="text-sm text-amber-600 dark:text-amber-300">
                  Store this file securely. Anyone with this kit and enough shares
                  can reconstruct your secret.
                </p>
              </div>
            </div>
          </div>

          {error && (
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
              <p className="text-sm text-destructive">{error}</p>
            </div>
          )}

          {success && (
            <div className="rounded-lg border border-green-500/50 bg-green-500/10 p-4">
              <p className="text-sm text-green-700 dark:text-green-400">
                Recovery kit downloaded successfully!
              </p>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button
            variant="ghost"
            onClick={() => setIsOpen(false)}
            disabled={isExporting}
          >
            Cancel
          </Button>
          <Button onClick={handleExport} disabled={isExporting}>
            {isExporting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Exporting...
              </>
            ) : (
              <>
                <Download className="mr-2 h-4 w-4" />
                Download Kit
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// frontend/src/lib/components/ExportRecoveryKitButton.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import * as Dialog from '$lib/components/ui/dialog';
  import { AlertCircle, Download, Loader2, ShieldCheck } from '@lucide/svelte';
  import { DEFAULT_RELAYS } from '$lib/nostr/relay-config';

  let {
    secret,
    threshold,
    totalShares,
    class: className
  }: {
    secret: {
      id: string;
      title: string;
      checkInDays: number;
      createdAt: Date | string;
      recipients: Array<{
        id: string;
        name: string;
        email: string | null;
        phone: string | null;
      }>;
    };
    threshold: number;
    totalShares: number;
    class?: string;
  } = $props();

  let isOpen = $state(false);
  let isExporting = $state(false);
  let error = $state<string | null>(null);
  let success = $state(false);

  async function handleExport() {
    isExporting = true;
    error = null;
    success = false;

    try {
      // Get CSRF token
      const csrfRes = await fetch('/api/csrf-token');
      const { token: csrfToken } = await csrfRes.json();

      const response = await fetch(`/api/secrets/${secret.id}/export-share`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-csrf-token': csrfToken
        },
        credentials: 'include'
      });

      if (!response.ok) {
        const errorData = await response.json().catch(() => ({}));
        if (response.status === 401) throw new Error('Session expired. Please log in again.');
        if (response.status === 404) throw new Error('Server share not found or has been deleted.');
        throw new Error(errorData.error || 'Failed to retrieve server share');
      }

      const shareData = await response.json();
      const serverShare = shareData.serverShare;

      // Get user-managed shares from localStorage
      const storedData = localStorage.getItem(`keyfate:userManagedShares:${secret.id}`);
      let userManagedShares: string[] = [];
      if (storedData) {
        try {
          const parsed = JSON.parse(storedData);
          if (parsed.expiresAt > Date.now()) {
            userManagedShares = parsed.shares || [];
          }
        } catch {
          // ignore parse errors
        }
      }

      // Fetch Bitcoin status (non-blocking — include if available)
      let bitcoinData: Record<string, unknown> | undefined;
      try {
        const btcRes = await fetch(`/api/secrets/${secret.id}/bitcoin-status`);
        if (btcRes.ok) {
          const btcStatus = await btcRes.json();
          if (btcStatus.enabled && btcStatus.utxo) {
            bitcoinData = {
              enabled: true,
              preSignedRecipientTx: btcStatus.utxo.preSignedRecipientTx ?? null,
              timelockBlocks: btcStatus.utxo.ttlBlocks,
              timelockDays: Math.round(btcStatus.utxo.ttlBlocks / 144),
              utxoTxId: btcStatus.utxo.txId,
              utxoOutputIndex: btcStatus.utxo.outputIndex,
              amountSats: btcStatus.utxo.amountSats
            };
          }
        }
      } catch {
        // Bitcoin data is optional — continue without it
      }

      // Nostr data: include relay list, symmetric keys (plaintextKs), and
      // passphrase bundle if stored locally.
      //
      // Recovery architecture (3 independent paths):
      //   1. Server path  — server share is included in this kit directly.
      //   2. Nostr path   — encrypted shares live on Nostr relays; plaintextKs
      //      (symmetric keys K) stored here allow offline decryption of those
      //      shares if the user has a local copy. Event IDs let the recovery
      //      UI fetch ciphertexts from relays as a fallback.
      //   3. Bitcoin path — pre-signed timelock transaction included separately.
      //
      // If BOTH the server AND all relays are down simultaneously, recovery
      // still works via the Bitcoin timelock (path 3) or if the user has the
      // passphrase to derive K from encryptedKPassphrase.
      let nostrData: Record<string, unknown> | undefined;
      const nostrStoredData = localStorage.getItem(`keyfate:nostrData:${secret.id}`);
      if (nostrStoredData) {
        try {
          const parsed = JSON.parse(nostrStoredData);
          nostrData = {
            enabled: true,
            eventIds: parsed.eventIds ?? [],
            plaintextKs: parsed.plaintextKs ?? [],
            relays: [...DEFAULT_RELAYS],
            encryptedKPassphrase: parsed.encryptedKPassphrase ?? null
          };
        } catch {
          // Nostr data is optional
        }
      }
      if (!nostrData) {
        // Include relay list even without stored event IDs
        nostrData = {
          enabled: false,
          eventIds: [],
          plaintextKs: [],
          relays: [...DEFAULT_RELAYS],
          encryptedKPassphrase: null
        };
      }

      // Build and download recovery kit
      const kitData: Record<string, unknown> = {
        metadata: {
          id: secret.id,
          title: secret.title,
          threshold,
          totalShares,
          checkInDays: secret.checkInDays,
          recipients: secret.recipients.map((r) => ({ name: r.name, email: r.email || '' })),
          createdAt:
            typeof secret.createdAt === 'string'
              ? secret.createdAt
              : secret.createdAt.toISOString(),
          exportedAt: new Date().toISOString()
        },
        serverShare,
        userManagedShares,
        ...(bitcoinData ? { bitcoin: bitcoinData } : {}),
        nostr: nostrData,
        recoveryInstructions:
          'Visit https://keyfate.com/recover to use this recovery kit. ' +
          'If KeyFate is unreachable, use the Bitcoin pre-signed transaction or ' +
          'the passphrase to recover the symmetric key K, then decrypt each share ' +
          'with ChaCha20-Poly1305 and combine using Shamir Secret Sharing.'
      };

      const blob = new Blob([JSON.stringify(kitData, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `keyfate-recovery-kit-${secret.title.replace(/\s+/g, '-').toLowerCase()}.json`;
      document.body.appendChild(a);
      a.click();
      URL.revokeObjectURL(url);
      document.body.removeChild(a);

      success = true;
      setTimeout(() => {
        isOpen = false;
        success = false;
      }, 2000);
    } catch (err) {
      console.error('Export error:', err);
      error = err instanceof Error ? err.message : 'Failed to export recovery kit';
    } finally {
      isExporting = false;
    }
  }
</script>

<Dialog.Root bind:open={isOpen}>
  <Dialog.Trigger>
    {#snippet child({ props })}
      <Button variant="outline" class={className} {...props}>
        <Download class="mr-2 h-4 w-4" />
        Export Recovery Kit
      </Button>
    {/snippet}
  </Dialog.Trigger>
  <Dialog.Content class="sm:max-w-md">
    <Dialog.Header>
      <Dialog.Title class="font-space flex items-center gap-2">
        <ShieldCheck class="text-primary h-5 w-5" />
        Export Recovery Kit
      </Dialog.Title>
      <Dialog.Description>
        Download a complete backup of your secret that works without KeyFate.
      </Dialog.Description>
    </Dialog.Header>

    <div class="space-y-4 py-4">
      <div class="bg-muted/50 rounded-lg p-4">
        <h4 class="font-space mb-2 font-medium">This kit includes:</h4>
        <ul class="text-muted-foreground space-y-1 text-sm">
          <li>&bull; Standalone recovery tool (works offline)</li>
          <li>&bull; Server share (decrypted)</li>
          <li>&bull; Your user-managed shares (if available)</li>
          <li>&bull; Bitcoin transaction data and timelock info (if enabled)</li>
          <li>&bull; Nostr relay list and encrypted key bundle</li>
          <li>&bull; Secret metadata and recovery instructions</li>
        </ul>
      </div>

      <div class="rounded-lg border border-destructive/30 bg-destructive/5 p-4">
        <div class="flex gap-2">
          <AlertCircle class="h-5 w-5 shrink-0 text-destructive" />
          <div>
            <h4 class="font-medium text-foreground">Security Notice</h4>
            <p class="text-sm text-muted-foreground">
              Store this file securely. Anyone with this kit and enough shares can reconstruct your
              secret.
            </p>
          </div>
        </div>
      </div>

      {#if error}
        <div class="border-destructive/50 bg-destructive/10 rounded-lg border p-4">
          <p class="text-destructive text-sm">{error}</p>
        </div>
      {/if}

      {#if success}
        <div class="rounded-lg border border-primary/50 bg-primary/10 p-4">
          <p class="text-sm text-primary">
            Recovery kit downloaded successfully!
          </p>
        </div>
      {/if}
    </div>

    <Dialog.Footer>
      <Button variant="ghost" onclick={() => (isOpen = false)} disabled={isExporting} class="">
        Cancel
      </Button>
      <Button onclick={handleExport} disabled={isExporting} class="">
        {#if isExporting}
          <Loader2 class="mr-2 h-4 w-4 animate-spin" />
          Exporting...
        {:else}
          <Download class="mr-2 h-4 w-4" />
          Download Kit
        {/if}
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
