// frontend/src/components/forms/newSecretForm.tsx
"use client"

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { UpgradeModal } from "@/components/upgrade-modal"
import { secretFormSchema, type SecretFormValues } from "@/lib/schemas/secret"
import { zodResolver } from "@hookform/resolvers/zod"
import { Buffer } from "buffer"
import {
  AlertCircle,
  AlertTriangle,
  Crown,
  Info,
  LockIcon,
  Plus,
  Trash2,
} from "lucide-react"
import { useRouter } from "next/navigation"
import { useState } from "react"
import { useFieldArray, useForm } from "react-hook-form"
import sss from "shamirs-secret-sharing"
import { ThresholdSelector } from "./ThresholdSelector"

interface NewSecretFormProps {
  isPaid?: boolean
  tierInfo?: {
    secretsUsed: number
    secretsLimit: number
    canCreate: boolean
    recipientsLimit: number
  }
}

export function NewSecretForm({
  isPaid = false,
  tierInfo,
}: NewSecretFormProps) {
  const router = useRouter()
  const [error, setError] = useState<string | null>(null)
  const [showUpgradeModal, setShowUpgradeModal] = useState(false)

  const form = useForm<SecretFormValues>({
    resolver: zodResolver(secretFormSchema),
    mode: "onBlur",
    defaultValues: {
      title: "",
      secretMessageContent: "",
      recipients: [{ name: "", email: "" }],
      check_in_days: "365",
      sss_shares_total: 3,
      sss_threshold: 2,
    },
  })

  const { isSubmitting } = form.formState

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: "recipients",
  })

  const maxRecipients = isPaid ? 5 : 1
  const canAddMore = fields.length < maxRecipients

  async function onSubmit(data: SecretFormValues) {
    setError(null)

    try {
      // 1. Perform SSS split client-side
      const secretBuffer = Buffer.from(data.secretMessageContent, "utf8")
      const shares = sss.split(secretBuffer, {
        shares: data.sss_shares_total,
        threshold: data.sss_threshold,
      })
      // Ensure enough shares were generated (should always be true if sss.split succeeded)
      if (shares.length < data.sss_shares_total || shares.length === 0) {
        throw new Error("Failed to generate the required number of SSS shares.")
      }

      // 2. Designate shares
      const userManagedShares = []
      // Start from shares[1] as shares[0] is for the server
      for (let i = 1; i < shares.length; i++) {
        userManagedShares.push(shares[i].toString("hex"))
      }

      // 3. Send plain server share to API for server-side encryption
      const serverSharePlainHex = shares[0].toString("hex")

      const payload = {
        title: data.title,
        server_share: serverSharePlainHex,
        recipients: data.recipients,
        check_in_days: parseInt(data.check_in_days, 10),
        sss_shares_total: data.sss_shares_total,
        sss_threshold: data.sss_threshold,
      }

      const response = await fetch("/api/secrets", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      })

      const result = await response.json()

      if (!response.ok) {
        throw new Error(result.error || "Failed to create secret via API")
      }

      if (!result.secretId) {
        throw new Error("API did not return a secret ID.")
      }

      if (result.warning) {
        setError(result.warning) // Display warning but proceed with redirect
      }

      // Store shares in localStorage with 2 hour expiry
      const expiresAt = Date.now() + 2 * 60 * 60 * 1000 // 2 hours in ms
      localStorage.setItem(
        `keyfate:userManagedShares:${result.secretId}`,
        JSON.stringify({ shares: userManagedShares, expiresAt }),
      )

      const queryParams = new URLSearchParams({
        secretId: result.secretId,
        sss_shares_total: data.sss_shares_total.toString(),
        sss_threshold: data.sss_threshold.toString(),
        recipients: encodeURIComponent(
          JSON.stringify(
            data.recipients.map((r) => ({ name: r.name, email: r.email })),
          ),
        ),
      })
      router.push(
        `/secrets/${result.secretId}/share-instructions?${queryParams.toString()}`,
      )
    } catch (err) {
      setError(
        err instanceof Error
          ? err.message
          : "An unknown error occurred while creating the secret.",
      )
      console.error("Submit error:", err)
    }
  }

  const percentageUsed = tierInfo
    ? (tierInfo.secretsUsed / tierInfo.secretsLimit) * 100
    : 0

  const showWarning = tierInfo && percentageUsed >= 75 && tierInfo.canCreate
  const isAtLimit = tierInfo && !tierInfo.canCreate

  return (
    <>
      {error && (
        <Alert variant="destructive" className="mb-6">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Error Creating Secret</AlertTitle>
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      {isAtLimit && (
        <Alert variant="destructive" className="mb-6">
          <AlertCircle className="h-4 w-4" />
          <AlertTitle>Secret Limit Reached</AlertTitle>
          <AlertDescription>
            You've used all {tierInfo.secretsLimit} of your{" "}
            {isPaid ? "Pro" : "Free"} tier secrets.
            {!isPaid && " Upgrade to Pro to create up to 10 secrets."}
          </AlertDescription>
        </Alert>
      )}

      {showWarning && (
        <Alert className="border-muted bg-muted/50 mb-6">
          <AlertTriangle className="text-muted-foreground h-4 w-4" />
          <AlertTitle className="text-foreground">Approaching Limit</AlertTitle>
          <AlertDescription className="text-muted-foreground">
            You're using {tierInfo.secretsUsed} of {tierInfo.secretsLimit}{" "}
            secrets ({Math.round(percentageUsed)}%).
            {!isPaid && " Consider upgrading to Pro for 10 secrets."}
          </AlertDescription>
        </Alert>
      )}

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
          {/* Secret Details Section */}
          <div className="space-y-4">
            <FormField
              control={form.control}
              name="title"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Secret Title</FormLabel>
                  <FormControl>
                    <Input
                      {...field}
                      placeholder="Example: Grandma's Recipe Book Location"
                      disabled={isSubmitting}
                    />
                  </FormControl>
                  <FormMessage />
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="secretMessageContent"
              render={({ field }) => (
                <FormItem>
                  <FormLabel className="flex items-center gap-1">
                    Secret Message
                    <LockIcon className="h-3 w-3" />
                  </FormLabel>
                  <FormControl>
                    <Textarea
                      {...field}
                      placeholder="Your secret message."
                      rows={4}
                      disabled={isSubmitting}
                    />
                  </FormControl>
                  <FormDescription className="text-xs">
                    This message will be split using Shamir's Secret Sharing.
                    You'll manage the shares on the next page.
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          {/* Recipient Information Section */}
          <div className="space-y-4 border-t pt-6">
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-medium text-muted-foreground">
                Recipients
              </h2>
              {!isPaid && fields.length >= 1 && (
                <Button
                  type="button"
                  variant="outline"
                  size="sm"
                  onClick={() => setShowUpgradeModal(true)}
                  className="gap-1.5 h-8 text-xs"
                >
                  <Crown className="h-3 w-3" />
                  Add More (Pro)
                </Button>
              )}
            </div>

            {isPaid &&
              maxRecipients > 0 &&
              fields.length >= Math.floor(maxRecipients * 0.75) && (
                <Alert className="border-muted bg-muted/50">
                  <AlertTriangle className="text-muted-foreground h-4 w-4" />
                  <AlertDescription className="text-muted-foreground text-sm">
                    {fields.length >= maxRecipients
                      ? `Maximum ${maxRecipients} recipients reached.`
                      : `Using ${fields.length} of ${maxRecipients} recipients.`}
                  </AlertDescription>
                </Alert>
              )}

            <div className="space-y-3">
              {fields.map((field, index) => (
                <div key={field.id} className="space-y-3 rounded-md border bg-muted/30 p-3">
                  <div className="flex items-center justify-between">
                    <div className="text-xs font-medium text-muted-foreground">
                      Recipient {index + 1}
                    </div>
                    {fields.length > 1 && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="sm"
                        onClick={() => remove(index)}
                        disabled={isSubmitting}
                        className="h-7 w-7 p-0"
                      >
                        <Trash2 className="h-3.5 w-3.5" />
                      </Button>
                    )}
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <FormField
                      control={form.control}
                      name={`recipients.${index}.name`}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs">Name</FormLabel>
                          <FormControl>
                            <Input
                              {...field}
                              placeholder="Jane Doe"
                              disabled={isSubmitting}
                              className="h-9"
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />

                    <FormField
                      control={form.control}
                      name={`recipients.${index}.email`}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel className="text-xs">Email</FormLabel>
                          <FormControl>
                            <Input
                              type="email"
                              {...field}
                              placeholder="recipient@example.com"
                              disabled={isSubmitting}
                              className="h-9"
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                </div>
              ))}

              {isPaid && canAddMore && (
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => append({ name: "", email: "" })}
                  disabled={isSubmitting}
                  className="w-full h-9 text-sm"
                >
                  <Plus className="mr-1.5 h-4 w-4" />
                  Add Recipient ({fields.length} / {maxRecipients})
                </Button>
              )}

              {isPaid && !canAddMore && (
                <div className="text-muted-foreground py-1.5 text-center text-xs">
                  Maximum {maxRecipients} recipients reached
                </div>
              )}
            </div>
          </div>

          {/* Check-in Settings Section */}
          <div className="space-y-4 border-t pt-6">
            <h2 className="text-sm font-medium text-muted-foreground">
              Check-in Settings
            </h2>
            <FormField
              control={form.control}
              name="check_in_days"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Trigger Deadline</FormLabel>
                  <FormControl>
                    <Select
                      onValueChange={field.onChange}
                      defaultValue={field.value}
                      disabled={isSubmitting}
                    >
                      <FormControl>
                        <SelectTrigger>
                          <SelectValue placeholder="Select frequency" />
                        </SelectTrigger>
                      </FormControl>
                      <SelectContent>
                        {isPaid ? (
                          <>
                            <SelectItem value="1">1 day</SelectItem>
                            <SelectItem value="3">3 days</SelectItem>
                            <SelectItem value="7">1 week</SelectItem>
                            <SelectItem value="14">2 weeks</SelectItem>
                            <SelectItem value="30">1 month</SelectItem>
                            <SelectItem value="90">3 months</SelectItem>
                            <SelectItem value="180">6 months</SelectItem>
                            <SelectItem value="365">1 year</SelectItem>
                            <SelectItem value="1095">3 years</SelectItem>
                          </>
                        ) : (
                          <>
                            <SelectItem value="7">1 week</SelectItem>
                            <SelectItem value="30">1 month</SelectItem>
                            <SelectItem value="365">1 year</SelectItem>
                          </>
                        )}
                      </SelectContent>
                    </Select>
                  </FormControl>
                  <FormDescription className="text-xs">
                    {isPaid
                      ? "How long until your secret is automatically disclosed. Checking in will start the timer over."
                      : "How long until your secret is automatically disclosed. Checking in will start the timer over. Upgrade to Pro for more interval options."}
                  </FormDescription>
                  <FormMessage />
                </FormItem>
              )}
            />
          </div>

          {/* Advanced Settings Section */}
          <div className="space-y-4 border-t pt-6">
            <Accordion
              type="single"
              collapsible
              className="w-full"
              defaultValue={fields.length > 1 ? "sss-config" : undefined}
            >
              <AccordionItem value="sss-config" className="border-0">
                <AccordionTrigger className="text-sm font-medium text-muted-foreground hover:text-foreground py-0 hover:no-underline">
                  Advanced Settings (optional)
                </AccordionTrigger>
                <AccordionContent className="space-y-3 pt-4">
                  {fields.length > 1 && (
                    <Alert>
                      <Info className="h-4 w-4" />
                      <AlertTitle className="text-sm">Multiple Recipients</AlertTitle>
                      <AlertDescription className="text-xs">
                        All recipients will receive the SAME share. You must
                        distribute this share to each recipient separately via
                        your own secure channels. With multiple recipients,
                        consider your threshold carefully.
                      </AlertDescription>
                    </Alert>
                  )}
                  <Alert>
                    <Info className="h-4 w-4" />
                    <AlertTitle className="text-sm">Secret Sharing Details</AlertTitle>
                    <AlertDescription className="text-xs">
                      <ul className="list-disc space-y-0.5 pl-5">
                        <li>
                          Your secret message will be split into a number of
                          cryptographic "shares".
                        </li>
                        <li>
                          A minimum number of shares (threshold) will be
                          required to reconstruct the original message.
                        </li>
                        <li>
                          KeyFate will securely store one share (encrypted again
                          by our server). You will manage the others on the next
                          page.
                        </li>
                      </ul>
                    </AlertDescription>
                  </Alert>
                  <ThresholdSelector
                    control={form.control}
                    isPro={isPaid}
                    isSubmitting={isSubmitting}
                    onUpgradeClick={() => setShowUpgradeModal(true)}
                  />
                </AccordionContent>
              </AccordionItem>
            </Accordion>
          </div>

          <Button
            type="submit"
            disabled={isSubmitting || isAtLimit}
            className="w-full"
          >
            {isSubmitting
              ? "Processing & Encrypting..."
              : isAtLimit
                ? "Secret Limit Reached - Upgrade Required"
                : "Create Secret & Proceed to Share Management"}
          </Button>
        </form>
      </Form>

      <UpgradeModal
        open={showUpgradeModal}
        onOpenChange={setShowUpgradeModal}
        feature="multiple recipients per secret"
        currentLimit="1 recipient"
        proLimit="Up to 5 recipients"
      />
    </>
  )
}

// frontend/src/lib/components/NewSecretForm.svelte
<script lang="ts">
  import { goto } from '$app/navigation';
  import * as Accordion from '$lib/components/ui/accordion';
  import * as Alert from '$lib/components/ui/alert';
  import { Button } from '$lib/components/ui/button';
  import { Input } from '$lib/components/ui/input';
  import { Label } from '$lib/components/ui/label';
  import * as Select from '$lib/components/ui/select';
  import { Textarea } from '$lib/components/ui/textarea';
  import UpgradeModal from '$lib/components/UpgradeModal.svelte';
  import ThresholdSelector from '$lib/components/ThresholdSelector.svelte';
  import MessageTemplateSelector from '$lib/components/MessageTemplateSelector.svelte';
  import { Checkbox } from '$lib/components/ui/checkbox';
  import NostrPubkeyInput from '$lib/components/NostrPubkeyInput.svelte';
  import {
    AlertCircle,
    AlertTriangle,
    Bitcoin,
    Crown,
    Info,
    Lock,
    Plus,
    Radio,
    Trash2
  } from '@lucide/svelte';
  import { Buffer } from 'buffer';
  import sss from 'shamirs-secret-sharing';

  let {
    isPaid = false,
    tierInfo
  }: {
    isPaid?: boolean;
    tierInfo?: {
      secretsUsed: number;
      secretsLimit: number;
      canCreate: boolean;
      recipientsLimit: number;
    };
  } = $props();

  let error = $state<string | null>(null);
  let showUpgradeModal = $state(false);
  let isSubmitting = $state(false);

  // Form state
  let title = $state('');
  let secretMessageContent = $state('');
  let recipients = $state<Array<{ name: string; email: string; nostrPubkey: string }>>([
    { name: '', email: '', nostrPubkey: '' }
  ]);
  let checkInDays = $state('365');
  let sssSharesTotal = $state(3);
  let sssThreshold = $state(2);

  // Bitcoin & Nostr settings (Pro only)
  let enableNostrShares = $state(false);
  let enableBitcoinTimelock = $state(false);

  // Validation errors
  let fieldErrors = $state<Record<string, string>>({});

  let maxRecipients = $derived(isPaid ? (tierInfo?.recipientsLimit ?? 5) : 1);
  let canAddMore = $derived(recipients.length < maxRecipients);

  let percentageUsed = $derived(
    tierInfo ? (tierInfo.secretsUsed / tierInfo.secretsLimit) * 100 : 0
  );
  let showWarning = $derived(tierInfo && percentageUsed >= 75 && tierInfo.canCreate);
  let isAtLimit = $derived(tierInfo && !tierInfo.canCreate);

  const CHECK_IN_OPTIONS: Array<{ value: string; label: string; paidOnly: boolean }> = [
    { value: '1', label: '1 day', paidOnly: true },
    { value: '3', label: '3 days', paidOnly: true },
    { value: '7', label: '1 week', paidOnly: false },
    { value: '14', label: '2 weeks', paidOnly: true },
    { value: '30', label: '1 month', paidOnly: false },
    { value: '90', label: '3 months', paidOnly: true },
    { value: '180', label: '6 months', paidOnly: true },
    { value: '365', label: '1 year', paidOnly: false },
    { value: '1095', label: '3 years', paidOnly: true }
  ];

  let availableOptions = $derived(
    CHECK_IN_OPTIONS.filter((opt) => isPaid || !opt.paidOnly)
  );

  let selectedCheckInLabel = $derived(
    CHECK_IN_OPTIONS.find((opt) => opt.value === checkInDays)?.label ?? 'Select frequency'
  );

  function addRecipient() {
    recipients = [...recipients, { name: '', email: '', nostrPubkey: '' }];
  }

  function removeRecipient(index: number) {
    recipients = recipients.filter((_, i) => i !== index) as typeof recipients;
  }

  function handleTemplateSelect(content: string) {
    secretMessageContent = content;
  }

  function isValidEmail(email: string): boolean {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
  }

  function validate(): boolean {
    const errors: Record<string, string> = {};

    if (!title.trim()) {
      errors.title = 'Title is required';
    }

    if (!secretMessageContent.trim()) {
      errors.secretMessageContent = 'Secret message is required';
    }

    if (recipients.length === 0) {
      errors.recipients = 'At least one recipient is required';
    }

    for (let i = 0; i < recipients.length; i++) {
      const r = recipients[i];
      if (!r.name.trim()) {
        errors[`recipient_${i}_name`] = 'Name is required';
      }
      if (!r.email.trim()) {
        errors[`recipient_${i}_email`] = 'Email is required';
      } else if (!isValidEmail(r.email)) {
        errors[`recipient_${i}_email`] = 'Invalid email address';
      }
    }

    if (sssSharesTotal < 3) {
      errors.sssSharesTotal = 'Minimum 3 shares required';
    }
    if (sssThreshold < 2) {
      errors.sssThreshold = 'Minimum threshold is 2';
    }
    if (sssThreshold > sssSharesTotal) {
      errors.sssThreshold = 'Threshold cannot exceed total shares';
    }

    fieldErrors = errors;
    return Object.keys(errors).length === 0;
  }

  async function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    error = null;
    isSubmitting = true;

    try {
      if (!validate()) {
        isSubmitting = false;
        return;
      }

      // SSS split client-side
      const secretBuffer = Buffer.from(secretMessageContent, 'utf8');
      const shares = sss.split(secretBuffer, {
        shares: sssSharesTotal,
        threshold: sssThreshold
      });

      if (shares.length < sssSharesTotal || shares.length === 0) {
        throw new Error('Failed to generate the required number of SSS shares.');
      }

      const userManagedShares: string[] = [];
      for (let i = 1; i < shares.length; i++) {
        userManagedShares.push(shares[i].toString('hex'));
      }

      const serverSharePlainHex = shares[0].toString('hex');

      // Get CSRF token
      const csrfRes = await fetch('/api/csrf-token');
      const { token: csrfToken } = await csrfRes.json();

      const payload = {
        title,
        server_share: serverSharePlainHex,
        recipients: recipients.map((r) => ({ name: r.name, email: r.email })),
        check_in_days: parseInt(checkInDays, 10),
        sss_shares_total: sssSharesTotal,
        sss_threshold: sssThreshold,
        enable_nostr_shares: enableNostrShares,
        enable_bitcoin_timelock: enableBitcoinTimelock,
        ...(enableNostrShares
          ? {
              recipient_nostr_pubkeys: recipients
                .filter((r) => r.nostrPubkey)
                .map((r) => ({ email: r.email, npub: r.nostrPubkey }))
            }
          : {})
      };

      const response = await fetch('/api/secrets', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-csrf-token': csrfToken
        },
        body: JSON.stringify(payload)
      });

      const result = await response.json();

      if (!response.ok) throw new Error(result.error || 'Failed to create secret via API');
      if (!result.secretId) throw new Error('API did not return a secret ID.');

      if (result.warning) {
        error = result.warning;
      }

      // Store shares in localStorage with 24 hour expiry
      const expiresAt = Date.now() + 24 * 60 * 60 * 1000;
      localStorage.setItem(
        `keyfate:userManagedShares:${result.secretId}`,
        JSON.stringify({ shares: userManagedShares, expiresAt })
      );

      // If Nostr shares are enabled, publish them and store the result for the recovery kit
      if (enableNostrShares && result.recipients?.some((r: { nostrPubkey: string | null }) => r.nostrPubkey)) {
        try {
          // Build share payloads for recipients that have nostr pubkeys
          const nostrRecipients = result.recipients.filter(
            (r: { nostrPubkey: string | null }) => r.nostrPubkey
          );
          const nostrShares = nostrRecipients.map(
            (r: { id: string }, idx: number) => ({
              share: userManagedShares[idx],
              shareIndex: idx + 1,
              recipientId: r.id
            })
          );

          const publishRes = await fetch(`/api/secrets/${result.secretId}/publish-nostr`, {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'x-csrf-token': csrfToken
            },
            body: JSON.stringify({
              shares: nostrShares,
              threshold: sssThreshold,
              totalShares: sssSharesTotal
            })
          });

          if (publishRes.ok) {
            const publishData = await publishRes.json();
            if (publishData.published?.length > 0) {
              // Take the first encryptedKPassphrase if any share has one
              const firstWithPassphrase = publishData.published.find(
                (p: { encryptedKPassphrase?: unknown }) => p.encryptedKPassphrase
              );

              localStorage.setItem(
                `keyfate:nostrData:${result.secretId}`,
                JSON.stringify({
                  eventIds: publishData.published.map((p: { nostrEventId: string }) => p.nostrEventId),
                  plaintextKs: publishData.published.map(
                    (p: { recipientId: string; plaintextK: string }) => ({
                      recipientId: p.recipientId,
                      plaintextK: p.plaintextK
                    })
                  ),
                  encryptedKPassphrase: firstWithPassphrase?.encryptedKPassphrase ?? null,
                  publishedAt: new Date().toISOString()
                })
              );
            }
          }
        } catch (nostrErr) {
          // Nostr publishing failure is non-fatal — the secret was already created
          console.error('Nostr publish failed (non-fatal):', nostrErr);
        }
      }

      const queryParams = new URLSearchParams({
        secretId: result.secretId,
        sss_shares_total: sssSharesTotal.toString(),
        sss_threshold: sssThreshold.toString(),
        recipients: encodeURIComponent(
          JSON.stringify(recipients.map((r) => ({ name: r.name, email: r.email })))
        )
      });

      goto(`/secrets/${result.secretId}/share-instructions?${queryParams.toString()}`);
    } catch (err) {
      error = err instanceof Error ? err.message : 'An unknown error occurred.';
      console.error('Submit error:', err);
    } finally {
      isSubmitting = false;
    }
  }
</script>

{#if error}
  <Alert.Root variant="destructive" class="mb-6">
    <AlertCircle class="h-4 w-4" />
    <Alert.Title>Error Creating Secret</Alert.Title>
    <Alert.Description>{error}</Alert.Description>
  </Alert.Root>
{/if}

{#if isAtLimit}
  <Alert.Root variant="destructive" class="mb-6">
    <AlertCircle class="h-4 w-4" />
    <Alert.Title>Secret Limit Reached</Alert.Title>
    <Alert.Description>
      You've used all {tierInfo?.secretsLimit} of your {isPaid ? 'Pro' : 'Free'} tier secrets.
      {#if !isPaid}{' '}Upgrade to Pro to create up to 10 secrets.{/if}
    </Alert.Description>
  </Alert.Root>
{/if}

{#if showWarning}
  <Alert.Root class="border-muted bg-muted/50 mb-6">
    <AlertTriangle class="text-muted-foreground h-4 w-4" />
    <Alert.Title class="text-foreground">Approaching Limit</Alert.Title>
    <Alert.Description class="text-muted-foreground">
      You're using {tierInfo?.secretsUsed} of {tierInfo?.secretsLimit} secrets ({Math.round(
        percentageUsed
      )}%).
      {#if !isPaid}{' '}Consider upgrading to Pro for 10 secrets.{/if}
    </Alert.Description>
  </Alert.Root>
{/if}

<form onsubmit={handleSubmit} class="space-y-8">
  <!-- Secret Details -->
  <div class="space-y-4">
    <div class="space-y-2">
      <Label for="title" class="text-xs font-medium text-muted-foreground">Secret Title</Label>
      <Input
        id="title"
        bind:value={title}
        placeholder="Example: Grandma's Recipe Book Location"
        disabled={isSubmitting}
      />
      {#if fieldErrors.title}
        <p class="text-destructive text-xs">{fieldErrors.title}</p>
      {/if}
    </div>

    <div class="space-y-2">
      <Label for="secretMessage" class="flex items-center gap-1 text-xs font-medium text-muted-foreground">
        Secret Message
        <Lock class="h-3 w-3" />
      </Label>
      <Textarea
        id="secretMessage"
        bind:value={secretMessageContent}
        placeholder="Your secret message."
        rows={4}
        disabled={isSubmitting}
      />
      <div class="flex items-center justify-between">
        <p class="text-muted-foreground text-xs">
          This message will be split using Shamir's Secret Sharing. You'll manage the shares on the
          next page.
        </p>
      </div>
      {#if fieldErrors.secretMessageContent}
        <p class="text-destructive text-xs">{fieldErrors.secretMessageContent}</p>
      {/if}
      <MessageTemplateSelector
        onSelectTemplate={handleTemplateSelect}
        isPro={isPaid}
        onUpgradeClick={() => (showUpgradeModal = true)}
      />
    </div>
  </div>

  <!-- Recipients -->
  <div class="space-y-4 pt-8">
    <div class="flex items-center justify-between">
      <h2 class="font-space text-lg font-bold tracking-tight">Recipients</h2>
      {#if !isPaid && recipients.length >= 1}
        <Button
          type="button"
          variant="outline"
          size="sm"
          onclick={() => (showUpgradeModal = true)}
          class="h-8 gap-1.5 text-xs"
        >
          <Crown class="h-3 w-3" />
          Add More (Pro)
        </Button>
      {/if}
    </div>

    {#if fieldErrors.recipients}
      <p class="text-destructive text-xs">{fieldErrors.recipients}</p>
    {/if}

    {#if isPaid && maxRecipients > 0 && recipients.length >= Math.floor(maxRecipients * 0.75)}
      <Alert.Root class="border-muted bg-muted/50">
        <AlertTriangle class="text-muted-foreground h-4 w-4" />
        <Alert.Description class="text-muted-foreground text-sm">
          {recipients.length >= maxRecipients
            ? `Maximum ${maxRecipients} recipients reached.`
            : `Using ${recipients.length} of ${maxRecipients} recipients.`}
        </Alert.Description>
      </Alert.Root>
    {/if}

    <div class="space-y-3">
      {#each recipients as recipient, index}
        <div class="space-y-3 rounded-md border border-border/50 p-4">
          <div class="flex items-center justify-between">
            <div class="text-xs font-medium text-muted-foreground">Recipient {index + 1}</div>
            {#if recipients.length > 1}
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onclick={() => removeRecipient(index)}
                disabled={isSubmitting}
                class="h-7 w-7 p-0"
              >
                <Trash2 class="h-3.5 w-3.5" />
              </Button>
            {/if}
          </div>

          <div class="grid grid-cols-2 gap-3">
            <div class="space-y-1">
              <Label for="recipient-{index}-name" class="text-xs font-medium text-muted-foreground">Name</Label>
              <Input
                id="recipient-{index}-name"
                bind:value={recipient.name}
                placeholder="Jane Doe"
                disabled={isSubmitting}
                class="h-9"
              />
              {#if fieldErrors[`recipient_${index}_name`]}
                <p class="text-destructive text-xs">{fieldErrors[`recipient_${index}_name`]}</p>
              {/if}
            </div>
            <div class="space-y-1">
              <Label for="recipient-{index}-email" class="text-xs font-medium text-muted-foreground">Email</Label>
              <Input
                id="recipient-{index}-email"
                type="email"
                bind:value={recipient.email}
                placeholder="recipient@example.com"
                disabled={isSubmitting}
                class="h-9"
              />
              {#if fieldErrors[`recipient_${index}_email`]}
                <p class="text-destructive text-xs">{fieldErrors[`recipient_${index}_email`]}</p>
              {/if}
            </div>
          </div>
        </div>
      {/each}

      {#if isPaid && canAddMore}
        <Button
          type="button"
          variant="outline"
          onclick={addRecipient}
          disabled={isSubmitting}
          class="h-9 w-full text-sm"
        >
          <Plus class="mr-1.5 h-4 w-4" />
          Add Recipient ({recipients.length} / {maxRecipients})
        </Button>
      {/if}

      {#if isPaid && !canAddMore}
        <div class="text-muted-foreground py-1.5 text-center text-xs">
          Maximum {maxRecipients} recipients reached
        </div>
      {/if}
    </div>
  </div>

  <!-- Check-in Settings -->
  <div class="space-y-4 pt-8">
    <h2 class="font-space text-lg font-bold tracking-tight">Check-in Settings</h2>
    <div class="space-y-2">
      <Label for="checkInDays" class="text-xs font-medium text-muted-foreground">Trigger Deadline</Label>
      <Select.Root type="single" bind:value={checkInDays}>
        <Select.Trigger>
          <span>{selectedCheckInLabel}</span>
        </Select.Trigger>
        <Select.Content>
          {#each availableOptions as option}
            <Select.Item value={option.value}>{option.label}</Select.Item>
          {/each}
        </Select.Content>
      </Select.Root>
      <p class="text-muted-foreground text-xs">
        {isPaid
          ? 'How long until your secret is automatically disclosed. Checking in will start the timer over.'
          : 'How long until your secret is automatically disclosed. Upgrade to Pro for more interval options.'}
      </p>
    </div>
  </div>

  <!-- Bitcoin & Nostr Settings (Pro) -->
  {#if isPaid}
    <div class="space-y-4 pt-8">
      <Accordion.Root type="single">
        <Accordion.Item value="bitcoin-nostr" class="border-0">
          <Accordion.Trigger
            class="text-muted-foreground hover:text-foreground py-0 text-sm font-medium hover:no-underline"
          >
            <span class="flex items-center gap-1.5">
              <Bitcoin class="h-3.5 w-3.5" />
              Bitcoin & Nostr (optional)
            </span>
          </Accordion.Trigger>
          <Accordion.Content class="space-y-4 pt-4">
            <Alert.Root>
              <Info class="h-4 w-4" />
              <Alert.Description class="text-xs">
                These features are optional and can be configured later from the secret detail page.
              </Alert.Description>
            </Alert.Root>

            <!-- Nostr share publishing toggle -->
            <div class="flex items-start gap-3 rounded-md border p-3">
              <Checkbox
                id="enable-nostr"
                bind:checked={enableNostrShares}
                disabled={isSubmitting}
              />
              <div class="space-y-1">
                <Label for="enable-nostr" class="flex items-center gap-1.5 text-sm font-medium">
                  <Radio class="h-3.5 w-3.5" />
                  Enable Nostr Share Publishing
                </Label>
                <p class="text-muted-foreground text-xs">
                  Deliver encrypted shares to recipients via Nostr direct messages (NIP-17).
                </p>
              </div>
            </div>

            {#if enableNostrShares}
              <div class="space-y-3 pl-6">
                {#each recipients as recipient, index}
                  <div class="bg-muted/30 rounded-md border p-3">
                    <p class="text-muted-foreground mb-2 text-xs font-medium">
                      {recipient.name || `Recipient ${index + 1}`} — Nostr Pubkey
                    </p>
                    <NostrPubkeyInput bind:value={recipient.nostrPubkey} />
                  </div>
                {/each}
              </div>
            {/if}

            <!-- Bitcoin timelock toggle -->
            <div class="flex items-start gap-3 rounded-md border p-3">
              <Checkbox
                id="enable-bitcoin"
                bind:checked={enableBitcoinTimelock}
                disabled={isSubmitting}
              />
              <div class="space-y-1">
                <Label for="enable-bitcoin" class="flex items-center gap-1.5 text-sm font-medium">
                  <Bitcoin class="h-3.5 w-3.5" />
                  Enable Bitcoin Timelock
                </Label>
                <p class="text-muted-foreground text-xs">
                  Lock BTC with a CSV timelock as an additional dead man's switch mechanism. Can be
                  configured after secret creation.
                </p>
              </div>
            </div>

            {#if enableBitcoinTimelock}
              <Alert.Root>
                <Info class="h-4 w-4" />
                <Alert.Description class="text-xs">
                  Bitcoin timelock will be configured on the secret detail page after creation.
                  You'll set the lock amount and fee priority there.
                </Alert.Description>
              </Alert.Root>
            {/if}
          </Accordion.Content>
        </Accordion.Item>
      </Accordion.Root>
    </div>
  {/if}

  <!-- Advanced Settings -->
  <div class="space-y-4 pt-8">
    <Accordion.Root type="single" value={recipients.length > 1 ? 'sss-config' : undefined}>
      <Accordion.Item value="sss-config" class="border-0">
        <Accordion.Trigger
          class="text-muted-foreground hover:text-foreground py-0 text-sm font-medium hover:no-underline"
        >
          Advanced Settings (optional)
        </Accordion.Trigger>
        <Accordion.Content class="space-y-3 pt-4">
          {#if recipients.length > 1}
            <Alert.Root>
              <Info class="h-4 w-4" />
              <Alert.Title class="text-sm">Multiple Recipients</Alert.Title>
              <Alert.Description class="text-xs">
                All recipients will receive the SAME share. You must distribute this share to each
                recipient separately via your own secure channels. With multiple recipients, consider
                your threshold carefully.
              </Alert.Description>
            </Alert.Root>
          {/if}
          <Alert.Root>
            <Info class="h-4 w-4" />
            <Alert.Title class="text-sm">Secret Sharing Details</Alert.Title>
            <Alert.Description class="text-xs">
              <ul class="list-disc space-y-0.5 pl-5">
                <li>
                  Your secret message will be split into a number of cryptographic "shares".
                </li>
                <li>
                  A minimum number of shares (threshold) will be required to reconstruct the
                  original message.
                </li>
                <li>
                  KeyFate will securely store one share (encrypted again by our server). You will
                  manage the others on the next page.
                </li>
              </ul>
            </Alert.Description>
          </Alert.Root>
          <ThresholdSelector
            bind:sharesTotalValue={sssSharesTotal}
            bind:thresholdValue={sssThreshold}
            isPro={isPaid}
            {isSubmitting}
            onUpgradeClick={() => (showUpgradeModal = true)}
            sharesTotalError={fieldErrors.sssSharesTotal}
            thresholdError={fieldErrors.sssThreshold}
          />
        </Accordion.Content>
      </Accordion.Item>
    </Accordion.Root>
  </div>

  <Button type="submit" disabled={isSubmitting || !!isAtLimit} class="w-full font-semibold">
    {isSubmitting
      ? 'Processing & Encrypting...'
      : isAtLimit
        ? 'Secret Limit Reached - Upgrade Required'
        : 'Create Secret & Proceed to Share Management'}
  </Button>
</form>

<UpgradeModal
  bind:open={showUpgradeModal}
  onOpenChange={(v) => (showUpgradeModal = v)}
  feature="multiple recipients per secret"
  currentLimit="1 recipient"
  proLimit="Up to 5 recipients"
/>
