// frontend/src/lib/components/PricingCard.svelte
<script lang="ts">
	import { Badge } from '$lib/components/ui/badge';
	import { Button } from '$lib/components/ui/button';
	import { getAmount } from '$lib/pricing';
	import { Check, Crown } from '@lucide/svelte';
	import PaymentMethodSelector from '$lib/components/PaymentMethodSelector.svelte';
	import StripeCheckoutButton from '$lib/components/StripeCheckoutButton.svelte';

	let {
		title,
		description,
		price,
		subtext,
		savingsText,
		features,
		buttonText,
		buttonHref,
		stripeLookupKey,
		billingPeriod,
		isPopular = false,
		class: className = '',
		userTier,
		userTierDisplayName
	}: {
		title: string;
		description: string;
		price: string;
		subtext?: string;
		savingsText?: string;
		features: string[];
		buttonText: string;
		buttonHref?: string;
		stripeLookupKey?: string;
		billingPeriod?: 'monthly' | 'yearly';
		isPopular?: boolean;
		class?: string;
		userTier?: string;
		userTierDisplayName?: string;
	} = $props();
</script>

<div class="flex flex-col {className}">
	<div class="pb-4 text-center">
		<div class="flex min-h-[40px] items-center justify-center space-x-2">
			{#if isPopular}
				<Crown class="text-primary h-5 w-5" />
			{/if}
			<h3 class="font-space text-xl font-bold">{title}</h3>
			{#if isPopular}
				<Badge variant="outline" class="text-xs tracking-wider uppercase">Most Popular</Badge>
			{/if}
		</div>
		<div class="mt-4 space-y-2 md:min-h-[120px]">
			<div class="font-space text-4xl font-light tracking-tight">{price}</div>
			{#if subtext}
				<p class="text-muted-foreground text-sm">{subtext}</p>
			{/if}
			{#if savingsText}
				<p class="text-success text-sm font-medium">{savingsText}</p>
			{/if}
			{#if description}
				<p class="text-muted-foreground text-sm">{description}</p>
			{/if}
		</div>
	</div>

	<div class="flex flex-1 flex-col space-y-4">
		<ul class="flex-1 space-y-3">
			{#each features as feature}
				<li class="flex items-start space-x-3">
					<Check
						class="{isPopular
							? 'text-success'
							: 'text-muted-foreground'} mt-0.5 h-4 w-4 flex-shrink-0"
					/>
					<span class="text-muted-foreground text-sm">{feature}</span>
				</li>
			{/each}
		</ul>

		{#if stripeLookupKey}
			{#if billingPeriod}
				<PaymentMethodSelector
					lookupKey={stripeLookupKey}
					amount={getAmount(billingPeriod === 'monthly' ? 'monthly' : 'yearly')}
					interval={billingPeriod === 'monthly' ? 'monthly' : 'yearly'}
					{userTier}
					{userTierDisplayName}
				/>
			{:else}
				<div class="space-y-2">
					<StripeCheckoutButton lookupKey={stripeLookupKey}>
						{buttonText}
					</StripeCheckoutButton>
					<p class="text-muted-foreground text-center text-xs">Sign up or log in to continue</p>
				</div>
			{/if}
		{:else if buttonHref}
			<Button
				class="w-full font-semibold"
				variant={isPopular ? 'default' : 'outline'}
				href={buttonHref}
			>
				{buttonText}
			</Button>
		{:else}
			<Button class="w-full font-semibold" variant={isPopular ? 'default' : 'outline'} disabled>
				{buttonText}
			</Button>
		{/if}
	</div>
</div>

// frontend/src/components/subscription/PricingCard.tsx
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { getAmount } from "@/lib/pricing"
import { Check, Crown } from "lucide-react"
import Link from "next/link"
import { PaymentMethodSelector } from "./PaymentMethodSelector"
import { StripeCheckoutButton } from "./StripeCheckoutButton"

interface PricingCardProps {
  title: string
  description: string
  price: string
  subtext?: string
  savingsText?: string
  features: string[]
  buttonText: string
  buttonHref?: string
  stripeLookupKey?: string
  billingPeriod?: "monthly" | "yearly"
  isPopular?: boolean
  className?: string
  userTier?: string
  userTierDisplayName?: string
}

export function PricingCard({
  title,
  description,
  price,
  subtext,
  savingsText,
  features,
  buttonText,
  buttonHref,
  stripeLookupKey,
  billingPeriod,
  isPopular = false,
  className = "",
  userTier,
  userTierDisplayName,
}: PricingCardProps) {
  return (
    <Card
      className={`${isPopular ? "border-primary" : ""} ${className} flex flex-col`}
    >
      <CardHeader className="pb-8 text-center">
        <div className="flex min-h-[40px] items-center justify-center space-x-2">
          {isPopular && <Crown className="text-primary h-6 w-6" />}
          <CardTitle className="text-2xl">{title}</CardTitle>
          {isPopular && (
            <Badge className="bg-accent/50 text-accent-foreground dark:bg-accent dark:text-accent-foreground">
              Most Popular
            </Badge>
          )}
        </div>
        <div className="space-y-2 md:min-h-[120px]">
          <div className="text-foreground text-4xl font-bold">{price}</div>
          {subtext && (
            <p className="text-muted-foreground text-sm">{subtext}</p>
          )}
          {savingsText && (
            <p className="text-success text-sm font-medium">{savingsText}</p>
          )}
          {description && (
            <p className="text-muted-foreground">{description}</p>
          )}
        </div>
      </CardHeader>

      <CardContent className="flex flex-1 flex-col space-y-6">
        <ul className="flex-1 space-y-3">
          {features.map((feature, index) => (
            <li key={index} className="flex items-start space-x-3">
              <Check className="text-success mt-0.5 h-5 w-5 flex-shrink-0" />
              <span className="text-foreground text-sm">{feature}</span>
            </li>
          ))}
        </ul>

        {/* Use StripeCheckoutButton for paid tiers, regular Link for free tier */}
        {stripeLookupKey ? (
          billingPeriod ? (
            <PaymentMethodSelector
              lookupKey={stripeLookupKey}
              amount={getAmount(
                billingPeriod === "monthly" ? "monthly" : "yearly",
              )}
              interval={billingPeriod === "monthly" ? "monthly" : "yearly"}
              userTier={userTier}
              userTierDisplayName={userTierDisplayName}
            />
          ) : (
            <div className="space-y-2">
              <StripeCheckoutButton lookupKey={stripeLookupKey}>
                {buttonText}
              </StripeCheckoutButton>
              <p className="text-muted-foreground text-center text-xs">
                Sign up or log in to continue
              </p>
            </div>
          )
        ) : buttonHref ? (
          <Button
            className="w-full"
            variant={isPopular ? "default" : "outline"}
            asChild
          >
            <Link href={buttonHref}>{buttonText}</Link>
          </Button>
        ) : (
          <Button
            className="w-full"
            variant={isPopular ? "default" : "outline"}
            disabled
          >
            {buttonText}
          </Button>
        )}
      </CardContent>
    </Card>
  )
}
